### ISSUE TITLE
gzip sitemap

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#112]
Currently its too big, google gets timeouts when downloading. Make a new endpoint sitemap.xml.gz it should make downloading much faster

**Comment by MartinKolarik** [comment]
The current endpoint does support gzip. Do you think Google doesn't send the `Accept-Encoding` header?

**Comment by jimaek** [comment]
I mean it has to respond to this URL https://www.jsdelivr.com/sitemap.xml.gz

**Comment by MartinKolarik** [comment]
I know what you mean but why? It's being gzipped now too.

**Comment by jimaek** [comment]
Thats how I can submit it to webmaster. I dont think they send the header.

Also:
"A sitemap file can't contain more than 50,000 URLs and must be no larger than 50 MB uncompressed."

**Comment by MartinKolarik** [comment]
Then we exceed both of their limits.

**Comment by jimaek** [comment]
Then we need gz files + sitemap index
