### ISSUE TITLE
going back on mobile

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#113]
> You know the ads when you watch porn on phone that won't let you go back?
> 
> Your side works pretty much the same way. Pressing back button on phone moves the page to the stage before animation, after which animation starts again.

**Comment by MartinKolarik** [comment]
What animation, what page, what URL?

**Comment by jimaek** [comment]
You cant exit the site with the back button, it always sends you back to the search input after an animation.

**Comment by MartinKolarik** [comment]
You may need to hit the back button multiple times if you use search, that's all. It works exactly as the old site.

**Comment by jimaek** [comment]
Nope, I pressed it 10 times and it just goes in circles top to bottom

**Comment by MartinKolarik** [comment]
Give me exact steps. Do you open the site directly or via a link? What exactly you do on the site before going back?

**Comment by jimaek** [comment]
Open the site directly in mobile Chrome. Enter jquery in search, click on it. Go back, goes back to homepage. Start clicking back and it goes in circles top to bottom.
