### ISSUE TITLE
Status page

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#119]
@jimaek what's the status on this?

**Comment by jimaek** [comment]
What do you want to see on that page? We have this https://jsdelivr1.statuspage.io/ but its 100% manual

**Comment by MartinKolarik** [comment]
http://status.digitalocean.com

**Comment by jimaek** [comment]
Then technically done! :p 
We have no incidents and everything must be updated manually.

**Comment by MartinKolarik** [comment]
They don't have automated uptime monitoring? I'm sure we had that before.

**Comment by jimaek** [comment]
This is what they support https://dl.dropboxusercontent.com/s/mmjcd5gx78x13y2/chrome_2017-09-02_13-02-27.png

We had a Pingdom account, not anymore

**Comment by MartinKolarik** [comment]
Ah so you need a separate service for that and we don't have any?

**Comment by jimaek** [comment]
Im paying for https://updown.io/ for monitoring. But it doesnt integrate with statuspage

**Comment by MartinKolarik** [comment]
None of the supported ones wants to sponsor us?

**Comment by jimaek** [comment]
only pingdom can to monitoring and they dont

**Comment by MartinKolarik** [comment]
Maybe we can use apex. Need to check how their status pages work.

**Comment by jimaek** [comment]
Where would we link to the status page? The site looks already busy as is

**Comment by MartinKolarik** [comment]
When we have updown monitoring, we can add links to updown pages to https://jsdelivr1.statuspage.io/ and move https://jsdelivr1.statuspage.io/ to status.jsdelivr.com.

**Comment by jimaek** [comment]
The value of statuspage is pulling external data and showing the charts along with status updates on a single page. But unfortunately it only works with the following https://dl.dropboxusercontent.com/s/3sdvsk8v1flib30/chrome_2019-01-09_18-22-06.png

**Comment by MartinKolarik** [comment]
It's not ideal but better than nothing - we'd have charts for everything powered by updown on separate pages and the status page would only have manual status updates + links to charts.

**Comment by MattIPv4** [comment]
It would certainly be nice to see the status page have some more love (moving it to status.jsdelivr.com, integrating it into the main site (literally just status indicator dot if space is an issue?)).

**Comment by MattIPv4** [comment]
@jimaek / @MartinKolarik What are your thoughts on the above?

**Comment by MartinKolarik** [comment]
I think we'll go either with my previous suggestion of having the status page for manual updates + links to separate updown pages or with building our own status page using the updown API (which would allow us to have all chars on one page). Either way, it'll probably need to wait a bit longer as we have other priorities right now.

**Comment by MartinKolarik** [comment]
Regarding 

> I disagree with the need to automate the status page (statuspage themselves discourage this)

I think the main advantage of having a status page is that it displays the monitoring results in real-time and shows historical metrics. For manual status updates only, it isn't much better than just using Twitter, which is why we didn't give this higher priority so far.

**Comment by MattIPv4** [comment]
@MartinKolarik I absolutely agree that metrics are useful to have on there, it is something I suggested adding. Status updates themselves should not be automated though as that gives the impression to users that you are aware of the issue when you might not be.

Having a proper status page for communicating status updates is important though over just using Twitter as it gives users a central place to refer to where they can view any status updates currently affecting the service, as well as the metrics and historical data all in one place.

The two things I think are missing from the status page linked above currently are:
 1. Component breakdown - When posting status updates to the page, having a component breakdown on the page will allow you to clearly mark which parts of the service are affected by any incident.
 2. Metrics - From my understanding of the above, you currently are looking at using updown which isn't supported by Statuspage for metrics. I would strongly suggest getting in touch with pingdom again about a sponsorship or even having a chat with Statuspage about implementing support for updown metrics.

An alternative to pingdom (or asking statuspage for updown support) is to use the statuspage API and updown's API (if they have one, i haven't checked) to manually post the data form updown to the statuspage for the metric displays?

**Comment by BirkhoffLee** [comment]
We can periodically pull data from https://updown.io/api and push to StatusPage with their Restful API https://developer.statuspage.io/#operation/getPagesPageIdMetrics. Updown offers webhook as well.

**Comment by jimaek** [comment]
Still working on the data visualization but I think the task can be closed https://status.jsdelivr.com/

**Comment by MartinKolarik** [comment]
It's not done and it's not linked anywhere yet, so not really.

**Comment by MartinKolarik** [comment]
The new design is months away so it should be added to the current one too.

**Comment by jimaek** [comment]
The page itself is live, so this fulfils this task. Adding it to new one is possible but I don't think its a huge priority. We didn't have status for many years, it can wait another 2 months
