### ISSUE TITLE
Update tweet

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#120]
Text says "bootstrap is the 5th most popular package on jsDelivr, with 700 397 652 CDN hits in the last month" but when clicking on tweet it uses the old # format

**Comment by MartinKolarik** [comment]
I know. Your text is too long :P

**Comment by jimaek** [comment]
Are you sure? https://dl.dropboxusercontent.com/s/7iaz0hqankcv9c0/chrome_2017-09-02_13-52-00.png

**Comment by MartinKolarik** [comment]
Depends on the package name and number of hits obviously. In some cases it was.

**Comment by jimaek** [comment]
In this case with lots of hits there is still 19 chars left. That would have to be a huge name to not fit. I think its safe

**Comment by MartinKolarik** [comment]
I could pick the text based on total length but IMHO the current format is better for Twitter anyway.

**Comment by jimaek** [comment]
Just use the same text everywhere and let the user edit it if it doesnt fit. but I think most projects will fit just fine

**Comment by MartinKolarik** [comment]
![screenshot_20170902-141349](https://user-images.githubusercontent.com/6192491/29995413-0eaff9b8-8fe9-11e7-8651-67470c47ac32.png)

What's wrong with the current text?

**Comment by jimaek** [comment]
I dont like this phrase "lodash is the #8 package "
