### ISSUE TITLE
source map files

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#121]
I vote on removing the warning message. Many people dont care about them, it adds clutter, and the :( makes it looks like a problem when its not.
instead we should show a message if there is no main file set

**Comment by MartinKolarik** [comment]
There is a message when there's no file set. And since we don't really want people using the short links, mainfiles are currently only useful for the UI.

**Comment by jimaek** [comment]
ok then I vote on removing them completely and use that space for the badge code like we do now on other projects

**Comment by MartinKolarik** [comment]
Aah looks like we're going to disagree on many things today 😆 . You can get the badge code on any project by clicking on the badge. Let's keep the message there and see how people react (btw, the default issue text also links to jsdelivr website :P).

**Comment by jimaek** [comment]
The point was not to show the badge code but hide the map warning, from what I've seen nobody cares about them :)

**Comment by MartinKolarik** [comment]
Good, so there wasn't really a point, since we already have the space available and might as well use it.

**Comment by jimaek** [comment]
Too much going on on the site, I think it makes it hard to browse. Keeping that space empty would be even better I think.
