### ISSUE TITLE
search improvements

### ISSUE THREAD

**Issue by Haroenv** [jsdelivr/www.jsdelivr.com#126]
- add `attributesToRetrieve` for better performance
- add highlighting with `_highlightResult`
- show the `deprecated` flag
- execute a search when someone enters from the URL

Let me know if you need some help with this

**Comment by MartinKolarik** [comment]
- we already do that
 - I'm aware of this feature but don't really like it and didn't want to use it
 - that might be a good idea, a PR definitely welcome if you can do it
 - we already do that: https://www.jsdelivr.com/?query=lodash

**Comment by Haroenv** [comment]
Ah, that's great, I didn't take the time yet to read the code, but wanted to be sure that the correct attributes are used. 

@julienbourdeau, how can you replicate the URL not causing a search (I actually don't have the issue, maybe it's browser-related)

**Comment by julienbourdeau** [comment]
I checked and actually I had a link pointing to a query with no results.

It would be nice to add message _"No results founds"_ if nothing matches.

**Comment by MartinKolarik** [comment]
>It would be nice to add message "No results founds" if nothing matches.

Absolutely 👍

**Comment by MartinKolarik** [comment]
Added the "no results found" message and also made the search faster by reducing the debounce time.

@Haroenv I wanted to add the `deprecated` flag as well, but it seems our results don't even include deprecated packages? Not sure why, but...
 - https://yarnpkg.com/en/packages?q=sl&p=1
 - https://www.jsdelivr.com/?query=sl

Yarn shows a deprecated package `sl`, our website doesn't.

**Comment by Haroenv** [comment]
Yarn is using `optionalFilters` to give a higher priority to exact matches. By default deprecated packages have a lower priority and thus harder to find. You can see how we did that on the yarnpkg/website repo
