### ISSUE TITLE
Search results include deleted packages?

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#130]
https://www.jsdelivr.com/?query=cookie-bar and https://yarnpkg.com/en/packages?q=cookie-bar&p=1 both show a package `cookie-bar` but there's no such package on npm: https://www.npmjs.com/package/cookie-bar

// cc @Haroenv

**Comment by Haroenv** [comment]
Yes, that is an issue we were going to tackle soon. See https://github.com/algolia/npm-search/issues/57 for more info

**Comment by MartinKolarik** [comment]
@Haroenv thanks. I'm going to close this and follow the linked issue then 👍
