### ISSUE TITLE
crawled page "not found"

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/www.jsdelivr.com#131]
Googled `jsdelivr`, clicked on first sub-link 'jsDelivr CDN'.  It forwards a few times (bad for ranking), & ends up at https://www.jsdelivr.com/projects/alohaeditor

**Comment by MartinKolarik** [comment]
We redirected all old URLs we could but there were about 150 out of the > 2100 URLs we couldn't redirect anywhere and it's up to Google to remove those now.
