### ISSUE TITLE
Banner and seo

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#132]
https://dl.dropboxusercontent.com/s/ard7p9k4pjmhmxw/chrome_2017-09-14_11-16-47.png

I think we need to move the description text higher than the banner text and/or make the banner text field tagged as something else that google wont consider as text for parsing

**Comment by MartinKolarik** [comment]
This happens only with a few links and the package description already is higher. I made several SEO improvements, so hopefully Google will use the correct text at some point and also change those 6 links to something more useful.
