### ISSUE TITLE
Stats version

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#138]
https://dl.dropboxusercontent.com/s/w1gz0343gdrw8ht/chrome_2017-10-21_16-30-08.png

This is kinda annoying. At first glance it looks like a bug. Only later you realize it shows different versions. I think they need to show the same version by default.

**Comment by MartinKolarik** [comment]
@Drgy let's change it to default to the most popular version and add another version dropdown there to allow changing it:
![image](https://user-images.githubusercontent.com/6192491/31967420-29c0f27c-b90e-11e7-9fa3-41f603acb886.png)
