### ISSUE TITLE
Fix title text overflow when package name is too long

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#141]
https://www.jsdelivr.com/package/npm/@webcomponents/webcomponentsjs

**Comment by Mist12345** [comment]
Hey, this should be an easy fix, what are you thinking? 

Making the text smaller
![image](https://user-images.githubusercontent.com/32372004/33409732-e4bdadba-d54a-11e7-8b85-d28041a7a534.png)

Breaking the package word
![image](https://user-images.githubusercontent.com/32372004/33409700-c113575c-d54a-11e7-9876-e392127f4ced.png)

or maybe you have something else in mind?

**Comment by MartinKolarik** [comment]
I was thinking `text-overflow: ellipsis` but yeah it's easy.

**Comment by Mist12345** [comment]
I'm going to leave this for somebody looking for a "good first issue". Presuming you're not in a rush, if it's not done in a couple weeks I'll come back and fix it.
