### ISSUE TITLE
can't find added package with Algolia search, is there a delay ?

### ISSUE THREAD

**Issue by eldk** [jsdelivr/www.jsdelivr.com#144]
Hello,

I have added those package : 

- https://cdn.jsdelivr.net/gh/spip/SPIP@spip-3.1.6/prive/javascript/jquery.autosave.min.js
- https://cdn.jsdelivr.net/gh/spip/SPIP@spip-3.1.6/prive/javascript/jquery.placeholder-label.min.js
- https://cdn.jsdelivr.net/gh/spip/SPIP@spip-3.1.6/prive/javascript/ajaxCallback.min.js

Sources : 

- https://github.com/spip/SPIP/tree/spip-3.1.6/prive/javascript/jquery.autosave.js
- https://github.com/spip/SPIP/tree/spip-3.1.6/prive/javascript/jquery.placeholder-label.js
- https://github.com/spip/SPIP/tree/spip-3.1.6/prive/javascript/ajaxCallback.min.js

They are in use and delivered, since yesterday.

But I can't find them with search.

Is there a delay for files been indexed and searchable ?

Am I missing something ?

Thanks,

Eric

**Comment by MartinKolarik** [comment]
The website search only works with npm packages so if you want your package to appear in the search results, you'll need to publish it to npm and use npm based links.

**Comment by eldk** [comment]
Ok, thanks
