### ISSUE TITLE
Show bandwidth per project stats

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#145]
Multiply number of hits for each file by its size and show the sum somewhere on the project page.

**Comment by jimaek** [comment]
Probably needs to be part of the API, to simplify things for everyone

**Comment by MartinKolarik** [comment]
Having it in the API would also allow us to make queries such as "top 10 packages by bandwidth" so that's good. On the other hand, we'd either need to change the format of all stats endpoints, or add "duplicate" endpoints for this. If we were do add this to the API, I'd update the log parser to store this data in the DB.

**Comment by jimaek** [comment]
" I'd update the log parser to store this data in the DB". What data? Why? The API could make the calculation on the fly and store in redis.

**Comment by MartinKolarik** [comment]
For "top X packages" we need it computed for every package and indexed somehow so simply storing it in the DB makes most sense.

**Comment by MartinKolarik** [comment]
It still needs to be added in the front-end once we update the API, so let's keep this issue open as well.

**Comment by MartinKolarik** [comment]
Where and how do we show this? We could add two more tables + the big chart but it wouldn't look good. Maybe some kind of switch between hits / bandwidth?

**Comment by jimaek** [comment]
The value of bandwidth data is not that high. So we should only implement it if its simple and cheap to maintain.

**Comment by MartinKolarik** [comment]
That is not a problem. I'm only thinking about the UI here.

**Comment by jimaek** [comment]
Closing as its already part of the new design. Discussion can continue there.
