### ISSUE TITLE
Add loading animation

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#156]
On slow internet connection the package page takes a while to load and there's no visual indication whether it's still loading or failed.

![screenshot 2018-02-07 10 28 32](https://user-images.githubusercontent.com/6192491/35908740-cfe0f84c-0bf1-11e8-887b-087a1027dc83.png)

**Comment by jimaek** [comment]
I assume its loading data.jsdelivr.com. Shouldn't most of the elements be visible but empty since its basic html?

**Comment by MartinKolarik** [comment]
Everything that isn't visible in the screenshot needs data from the API.

**Comment by MartinKolarik** [comment]
And the parts that need data from API are visible only after we get the data, otherwise it would look even more broken.
