### ISSUE TITLE
Proxy blog

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#167]
We need to proxy /blog/ to jsdelivr-blog.ghost.io
I am removing Fly that was doing this because of their instability

**Comment by MartinKolarik** [comment]
Looks like we lost http -> https redirect again.

**Comment by jimaek** [comment]
enabled

**Comment by jimaek** [comment]
@MartinKolarik Can you work on this task with priority please? Without this our blog is down

**Comment by MartinKolarik** [comment]
Any good reason for not linking to https://jsdelivr-blog.ghost.io/ directly or using a subdomain? Using `/blog/` is going to be too complicated.

**Comment by jimaek** [comment]
SEO. Why complicated? Something like this should work just fine https://github.com/chimurai/http-proxy-middleware

**Comment by MartinKolarik** [comment]
Because of relative paths in HTML/CSS/JS. E.g. CSS referenced as `/assets/styles/main.css` will get loaded from `jsdelivr.com/assets/styles/main.css` (no `/blog/`).

**Comment by MartinKolarik** [comment]
We'd either have to forward all 404 request to the blog (hard) or attempt to rewrite all links on the fly (even harder).

**Comment by jimaek** [comment]
Doesnt the proxy package support all that? Even with Nginx its not hard to do
