### ISSUE TITLE
Add Frankfurt location to network infographic, add PerfOps

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#173]
https://www.jsdelivr.com/network/infographic

**Comment by jimaek** [comment]
Current system is Frankfurt, Amsterdam and Nuremberg. We can also show somehow that they are all interconnected between them with a mesh network. For example if the origin container in Frankfurt is down and user hits Frankfurt his request will be internally redirected to another container on the network.

**Comment by MartinKolarik** [comment]
Remove Cedexis, add PerfOps when we switch.
