### ISSUE TITLE
Enable HSTS

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#177]
It will also apply to subdomains, including https://github.com/jsdelivr/data.jsdelivr.com

**Comment by MartinKolarik** [comment]
Keeping this open until we increase max age and include preload.

**Comment by jimaek** [comment]
For what domains?

**Comment by MartinKolarik** [comment]
jsdelivr.com including subdomains

**Comment by jimaek** [comment]
Done

**Comment by MartinKolarik** [comment]
I think those redirects are in CF? We need http://jsdelivr.com -> https://www.jsdelivr.com

![image](https://user-images.githubusercontent.com/6192491/43336718-3390ace6-91d2-11e8-94b0-5bf59416c031.png)

**Comment by jimaek** [comment]
https://dl.dropboxusercontent.com/s/nrwlgoy5pxzdymm/chrome_2018-07-27_19-29-59.png
