### ISSUE TITLE
Purge cache on version range when publishing new package

### ISSUE THREAD

**Issue by leifriksheim** [jsdelivr/www.jsdelivr.com#179]
At the time we're using jsDelivr with a major tag like this:
https://cdn.jsdelivr.net/npm/our-package@6/

When releasing 6.0.1 we're still getting the cached version from 6.0.0.
It would be nice to purge cache on version range every time a new version is published on that range.
This also applies to tagged versions.

**Comment by MartinKolarik** [comment]
Right now this happens within 24 hours but we [do have an API](https://github.com/jsdelivr/jsdelivr#purge-cache) you can use to purge specific URLs immediately.

**Comment by leifriksheim** [comment]
Okey, thank's 👍 

I will set up a server, listen for releases and purge the cache manually, but I it would be nice with a feature to do this without having to do it manually or setting up a server yourself.

**Comment by MartinKolarik** [comment]
You don't need a server for that, just add one `curl` to your release script right after `npm publish`.

**Comment by rluvaton** [comment]
> Right now this happens within 24 hours but we [do have an API](https://github.com/jsdelivr/jsdelivr#purge-cache) you can use to purge specific URLs immediately.

What's the API endpoint?

**Comment by MartinKolarik** [comment]
> What's the API endpoint?

Read instructions at the link you just quoted.

**Comment by rluvaton** [comment]
> Read instructions at the link you just quoted.

I read but it says to send an email, and from this conversation, I understand there is an endpoint

**Comment by MartinKolarik** [comment]
Yes, please ask for it via email 😄

**Comment by Nashorn** [comment]
> You don't need a server for that, just add one `curl` to your release script right after `npm publish`.

could you provide snippet/example?

**Comment by marcmetz** [comment]
@jsdelivrbot purge https://cdn.jsdelivr.net/gh/meetanyway/globekit/examples/datapoints/js/datapoints.js
