### ISSUE TITLE
Add Foundation CDN page

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#197]
https://github.com/jsdelivr/foundationcdn

**Comment by MartinKolarik** [comment]
Should be a new page available at `/foundationcdn`. Design similar to the linked repo but needs to be coded like the rest of this website - ractive + our API for getting data if needed. Ping me on Skype with anything that isn't clear.

**Comment by jimaek** [comment]
Redirect updated
