### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by yusufshakeel** [jsdelivr/www.jsdelivr.com#204]
[This package](https://www.jsdelivr.com/package/npm/dyyoutubelazyloadjs) was not found on jsDelivr CDN, but it should have been.
Project NPM [link](https://www.npmjs.com/package/dyyoutubelazyloadjs).
Project GitHub [link](https://github.com/yusufshakeel/dyYouTubeLazyLoadJS)

**Comment by aliglelo** [comment]
Wait for a few hours
I also faced this issue
But it automatically resolves after few hours of problems..
I hope your problem will also resolve soon

**Comment by MartinKolarik** [comment]
The package was released only two days ago so this is most likely caused by [an issue our search provider is experiencing](https://status.yarnpkg.com/). According to the status page, it should be resolved this week.

**Comment by yusufshakeel** [comment]
Looks like the issue is resolved. I can now see the project on jsDelivr.
[Link](https://cdn.jsdelivr.net/npm/dyyoutubelazyloadjs@0.2.4/dist/js/dyYouTubeLazyLoad.min.js)
