### ISSUE TITLE
Packages not showing up on website

### ISSUE THREAD

**Issue by advaith1** [jsdelivr/www.jsdelivr.com#210]
Whenever I try to view a package page it starts to load but then the page changes to this:

> Package NAME was not found.
There might be a problem with your internet connection. Try refreshing the page a few times.
If the problem persists you can report it at our issue tracker.

I get this for multiple packages and according to all the "Package not found" issues made recently this affects many/all packages.

**Comment by MartinKolarik** [comment]
Should work now, sorry for the inconvenience.

**Comment by MartinKolarik** [comment]
It was caused by an issue with our API, we'll be in touch with Clever Cloud to see what happened exactly.
