### ISSUE TITLE
deepFreeze not found

### ISSUE THREAD

**Issue by Afrowave** [jsdelivr/www.jsdelivr.com#224]
[DdeepFreeze](https://www.jsdelivr.com/package/npm/deep-freeze) was not found on jsDelivr CDN, but it should have been.

Is there a link one can embed in project for testing?

**Comment by MartinKolarik** [comment]
> Is there a link one can embed in project for testing?

What do you mean exactly?

**Comment by Afrowave** [comment]
I was looking for something like this - [How to use this library in the web front-end](https://github.com/substack/deep-freeze/issues/14).

I got the answer here. There is no CDN hosting of deepFreeze. Is that still the case?

**Comment by MartinKolarik** [comment]
The link is https://cdn.jsdelivr.net/npm/deep-freeze@0.0.1/index.js but it's in AMD format. The author doesn't provide other formats.

**Comment by Afrowave** [comment]
I see. I will use the "expected" method - through NPM. Thanks @MartinKolarik.
