### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by persLaunch** [jsdelivr/www.jsdelivr.com#225]
[This package](https://www.jsdelivr.com/package/npm/switlish-plugin-put-aside) was not found on jsDelivr CDN, but it should have been.

**Comment by MartinKolarik** [comment]
The package has only been published recently and it seems our search provider hasn't indexed it yet. It should happen very soon but you can also browse the files directly on the CDN if needed: https://cdn.jsdelivr.net/npm/switlish-plugin-put-aside/ (CDN has no delay).
