### ISSUE TITLE
Stats page

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#25]
Some info that we could display on that page:
- Load balancing decisions for last 30 days per CDN (Cedexis)
- Performance of jsDelivr around the globe (Cedexis)
- Total CDN hits for the last 30 days (per provider and combined)
- Total bandwidth served (per provider and combined)
- Number of DNS requests for the last 30 days
- Number of hosted projects
- Top 15 projects per number of requests.

Any other ideas?

**Comment by moay** [comment]
Like all of the ideas. I would also like per project statistics. Just if this is still in the makings... ;-)

**Comment by jimaek** [comment]
Here is what we have so far http://www-jsdelivr-com.dak.netdna-cdn.com/statistics

**Comment by moay** [comment]
Coming back to this a few months later. I'd love to see, how many places my project is used in and how many users actually are served by jsdelivr. Is this possible somehow?

**Comment by jimaek** [comment]
There is a basic version in the works that can show number of hits per day per project.
The rest that you mentioned is related to this https://github.com/jsdelivr/jsdelivr/issues/7426
