### ISSUE TITLE
Package not found: copee

### ISSUE THREAD

**Issue by styfle** [jsdelivr/www.jsdelivr.com#253]
[This package](https://www.jsdelivr.com/package/npm/copee) was not found on jsDelivr CDN, but it should have been.

This is the console.error:

> Access to XMLHttpRequest at 'https://data.jsdelivr.com/v1/package/npm/copee' from origin 'https://www.jsdelivr.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by MartinKolarik** [comment]
Probably a temporary API issue, looks ok now.
