### ISSUE TITLE
Seroius attack on Git

### ISSUE THREAD

**Issue by aliglelo** [jsdelivr/www.jsdelivr.com#256]
Hello sir ,
I am happy user of Jsdelivr that is why I want Jsdelvr the most secured and safe cdn 
today i came across following article:
https://fossbytes.com/github-gitlab-bitbucket-repositories-hit-by-ransomware-demanding-bitcoin/
### Here is the search result currently showing 326 repos infected:
https://github.com/search?q=1ES14c7qLb5CYhLMUekctxLgc1FV2Ti9DA&type=Code

****
### Disclaimer : I dont want to creat any panic or any damage to either git or Jsdelivr but i am just helping to keep it secure.

**Comment by DanielRuf** [comment]
Hi, the incident happened because people stored the credentials in `.git/config` which is a really bad idea.
