### ISSUE TITLE
Design improvements

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#260]
I plan to talk with the designer about making some improvements. Bellow are mine but feel free to add your own and I will pass them:

1. [x] Too hard to find a link to our Github on the website. Need to find a good place for it. *Added to the top menu. Lets add Twitter there as well and remove both from footer*.

2. [x] We have a really cool infographic but its hidden behind a very small "how it works" button. Need to make it more prominent and visible. *See design below*.

3. [x] ~Maybe make the "network" page a separate page~. Show a bigger map and move all text below. *See the design below*.

4. [x] Remove about, tos and privacy from the features page. *Move all to footer*.

5. [x] Include infographic in a better way in the Features pages. *See the design below*.

6. Design purge cache tool page. Probably an input field asking for a list of URLs to purge, with "Purge Now" button and a captcha + ratelimit per IP on our side. After purge show pretty output of our results json: *Will be done in a separate issue*.

```
{
"fastly": [
{
"status": "ok",
"id": "20727-1558573413-986072"
},
{
"status": "ok",
"id": "20726-1558577588-1041027"
},
{
"status": "ok",
"id": "20726-1558577588-1041028"
},
{
"status": "ok",
"id": "20726-1558577588-1041029"
},
{
"status": "ok",
"id": "20734-1558573890-1049626"
},
{
"status": "ok",
"id": "20735-1558578641-958658"
}
],
"maxcdn": {
"code": 200
},
"cloudflare": true,
"quantil": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<response><message>success</message></response>"
}
```

**Comment by MartinKolarik** [comment]
> Remove about, tos and privacy from the features page

Where do you want to link them? They are already not easy enough to find.

**Comment by jimaek** [comment]
In the footer as is the standard for such pages. Forgot to include that

**Comment by jimaek** [comment]
![Homepage](https://user-images.githubusercontent.com/1834071/60545134-a4bbea80-9d1a-11e9-89c5-942ec7fb1b02.png)
![Network](https://user-images.githubusercontent.com/1834071/60545136-a4bbea80-9d1a-11e9-9218-068e449c52f1.png)
![Purge cache](https://user-images.githubusercontent.com/1834071/60545158-af767f80-9d1a-11e9-897f-86cda09098f1.png)
![Purge cache-1](https://user-images.githubusercontent.com/1834071/60545160-b00f1600-9d1a-11e9-960f-57adee4dea4e.png)
![Purge cache-2](https://user-images.githubusercontent.com/1834071/60545161-b00f1600-9d1a-11e9-926c-06ec190c9287.png)
![Purge cache-3](https://user-images.githubusercontent.com/1834071/60545162-b00f1600-9d1a-11e9-85ab-c3d47910b3d9.png)

**Comment by jimaek** [comment]
New updates

![Network](https://user-images.githubusercontent.com/1834071/60956751-b5b0c100-a303-11e9-9521-69e6360e8e91.png)
![Purge cache](https://user-images.githubusercontent.com/1834071/60956752-b5b0c100-a303-11e9-8780-df34e2c35aed.png)
![Purge cache-1](https://user-images.githubusercontent.com/1834071/60956754-b5b0c100-a303-11e9-9156-219b7dcf9deb.png)
![Purge cache-2](https://user-images.githubusercontent.com/1834071/60956755-b5b0c100-a303-11e9-990a-ff5d7c77e062.png)
![Purge cache-3](https://user-images.githubusercontent.com/1834071/60956756-b6495780-a303-11e9-85b6-5cf2b57eca46.png)

**Comment by MartinKolarik** [comment]
![60545136-a4bbea80-9d1a-11e9-9218-068e449c52f1](https://user-images.githubusercontent.com/6192491/60963375-e4816400-a310-11e9-9a90-60c5a49583e7.png)

Also, I'd keep the button below the textarea and make the textarea at least two lines even when empty so that it's clear it isn't a one-line input. The table design should probably match this: https://www.jsdelivr.com/unpkg

**Comment by jimaek** [comment]
Do you want me to ask the designer to update these or you do it as is?
Do you need the design in avocode?

**Comment by MartinKolarik** [comment]
I think we don't need the design updated, just the Chinese picture. And if you post the pics export here we don't need avocode.

**Comment by jimaek** [comment]
The chinese picture is only the background, the text is html text. So I think there is nothing to update?

**Comment by MartinKolarik** [comment]
Ah that makes it more annoying to code but probably makes sense. The flag is part of the background though, right?

**Comment by jimaek** [comment]
I thought it wasnt, if the flag is part of the text its easier to move it on different screen sizes without breaking.

**Comment by MartinKolarik** [comment]
Indeed, ok.

**Comment by MartinKolarik** [comment]
@Drgy check the first comment for a summary of changes but also read all the comments below.
