### ISSUE TITLE
Convert GitHub link to jsDelivr

### ISSUE THREAD

**Issue by FranklinYu** [jsdelivr/www.jsdelivr.com#270]
We can have some widget on the site converting

https://github.com/jquery/jquery/blob/3.2.1/dist/jquery.min.js

to

https://cdn.jsdelivr.net/gh/jquery/jquery@3.2.1/dist/jquery.min.js

**Comment by MartinKolarik** [comment]
Should be similar to https://www.jsdelivr.com/rawgit but at /github

**Comment by MartinKolarik** [comment]
Also support this format: https://raw.githubusercontent.com/jquery/jquery/3.2.1/dist/jquery.min.js

**Comment by MartinKolarik** [comment]
Available at https://jsdelivr.com/github, not sure yet where we'll link it.

**Comment by FranklinYu** [comment]
Do you consider it helpful to (optionally?) convert branch name to hash? The legacy RawGit does this.

Not sure whether it’s feasible to do this purely client-side; maybe we can make use of GitHub API?

**Comment by MartinKolarik** [comment]
@FranklinYu it might be useful. If you would like to, feel free to send a PR adding a switch for that above the "see all features" button. Design/code for switches can be copied from https://www.jsdelivr.com/network and I believe https://www.jsdelivr.com/rawgit already interacts with the GH API.

**Comment by mattrossman** [comment]
Has this been linked anywhere yet? This is such a useful feature of other CDNs, is there any reason it's not already linked on the homepage under the GitHub documentation?

**Comment by MartinKolarik** [comment]
@mattrossman added to the nav and footer now!
