### ISSUE TITLE
Add purge tool

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#274]
A new page at https://www.jsdelivr.com/tools/purge. Design at https://github.com/jsdelivr/www.jsdelivr.com/issues/260#issuecomment-509980806. Limit to 10 links. Ask for API access details in a PM.

**Comment by BirkhoffLee** [comment]
If you can PM me the details of API I might be able to implement this. However I can't design frontend look. @MartinKolarik

**Comment by jimaek** [comment]
Actually we already have the API implemented. So this task is mostly about the integration to the frontend. But we probably need to add IP rate-limiting and captcha validation, maybe you could help there?

**Comment by BirkhoffLee** [comment]
Yes. I just looked up [reCAPTCHA docs](https://developers.google.com/recaptcha/docs/faq#are-there-any-qps-or-daily-limits-on-my-use-of-recaptcha) and saw this:

> Are there any QPS or daily limits on my use of reCAPTCHA?  
>
>  If you wish to make more than 1k calls per second or 1m calls per month, you must use reCAPTCHA Enterprise or fill out this form and wait for an exception approval.

Shouldn't be a problem though

**Comment by jimaek** [comment]
I mean our own rate-limiting to the purge API, so that people won't abuse it

**Comment by BirkhoffLee** [comment]
Yes, sure

**Comment by MartinKolarik** [comment]
> Actually we already have the API implemented. So this task is mostly about the integration to the frontend.

@Drgy was working on that a while back and I think the frontend is mostly prepared but we run into issues regarding the captcha since it needs to be integrated with the API server-side so this got paused until we finalize the API.

**Comment by jimaek** [comment]
@BirkhoffLee would you be interested to handle the backend as well for this task?

**Comment by BirkhoffLee** [comment]
As stated in the email, yes I'd love to.

**Comment by BirkhoffLee** [comment]
Is there any specifications for rate-limiting? How do you want them to work?

**Comment by jimaek** [comment]
@BirkhoffLee I invited you to the repo and we have a task there with the details

**Comment by MartinKolarik** [comment]
@BirkhoffLee I pushed part of the front-end that @Drgy worked on before here to branch gh-274 in case you would like to continue with that. It was a work in progress so if you find something in there that doesn't look right you should probably change it but it should be easier than doing the UI from scratch.

**Comment by BirkhoffLee** [comment]
Where do I access gh-274? Like should there be an URL that was put online by CD

**Comment by MartinKolarik** [comment]
Deploy previews are only created once a PR is open.

**Comment by Drgy** [comment]
Hi @BirkhoffLee, I went through the changes in your pull request (#329) and I'm unable to find anything that would change/extend functionality from this branch, correct me please if I missed something. 
The reason the purge tool wasn't finished is missing backend for recaptcha, I don't have any information if this was resolved or not, but perhaps @MartinKolarik knows more. 
On frontend the recaptcha is correctly implemented and generating token which we need for verification. However to complete the verification this token needs to be sent to backend, which will in combination with secret key verify the user and send response to frontend. 
More about recaptcha is on google docs [here is the frontend implementation](https://developers.google.com/recaptcha/docs/display) (already implemented) and [here is what we need on backend](https://developers.google.com/recaptcha/docs/verify) (needs to be implemented).

**Comment by Drgy** [comment]
recaptcha is now working on [gh-274](https://github.com/jsdelivr/www.jsdelivr.com/tree/gh-274), @BirkhoffLee let me know if you will be able to take it from here.

**Comment by jimaek** [comment]
Integrated and redesigned in the new branch
