### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by stevenjoezhang** [jsdelivr/www.jsdelivr.com#285]
[This package](https://www.jsdelivr.com/package/npm/social-share.js) was not found on jsDelivr CDN, but it should have been.

**Comment by MartinKolarik** [comment]
Looks good now?

**Comment by MartinKolarik** [comment]
Note that the package has a nonexistent file set as `main` but you'll probably want one of these two: https://www.jsdelivr.com/package/npm/social-share.js?path=dist%2Fjs

**Comment by stevenjoezhang** [comment]
Thanks 😊
