### ISSUE TITLE
Change author link for GitHub projects to user's profile page

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [jsdelivr/www.jsdelivr.com#288]
There is a link on eg. page https://www.jsdelivr.com/package/gh/HashHackers/logo

The link goes to https://www.jsdelivr.com/?query=author%3A%20HashHackers which shows 0 results.

**Comment by MartinKolarik** [comment]
Indeed, we shouldn't display that link for GitHub projects.

**Comment by ParveenBhadooOfficial** [comment]
It should otherwise it should be removed for GitHub Only Projects from jsdelivr. Because its better not have a link then empty page.
