### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by farzbood** [jsdelivr/www.jsdelivr.com#293]
[This package](https://www.jsdelivr.com/package/npm/gasparesganga-jquery-loading-overlay) was not found on jsDelivr CDN, but it should have been.

**Comment by farzbood** [comment]
Why you then put a link in the site for reporting, when you're not going to respond?!!! :/

**Comment by MartinKolarik** [comment]
Does it still not work for you?

**Comment by farzbood** [comment]
I just tried to access the associated project's page through author's()
link below:
https://gasparesganga.com/labs/jquery-loading-overlay/#get-it
under, " CDN configuration page "
<https://www.jsdelivr.com/package/npm/gasparesganga-jquery-loading-overlay>
but the url, redirect me to this page (yours):
https://www.jsdelivr.com/package/npm/gasparesganga-jquery-loading-overlay
and there's the " Package gasparesganga-jquery-loading-overlay was not
found"  message and the link to "Reporting".
So, no it's not working.
Regards

**Comment by MartinKolarik** [comment]
Try to disable any browser extensions or use a different browser.
