### ISSUE TITLE
Update sponsor

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#305]
Need to move ClouDNS to Gold sponsors thanks to some new features they unlocked for us.

Better logo:
![logo-cloudns](https://user-images.githubusercontent.com/1834071/73748545-f2d61800-4759-11ea-88cf-daaf64393647.png)

**Comment by MartinKolarik** [comment]
Text?

**Comment by jimaek** [comment]
ClouDNS is offering Premium, DDoS Protected, and GeoDNS services supported by Global Anycast network.
