### ISSUE TITLE
Remove sponsor - Update infographic

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#311]
- [x]  Remove perfops logos everywhere
- [x]  Remove js tag
- [x]  Remove js tag call to action, but leave the benchmark
- [x]  Update infographic (need to discuss how)

**Comment by jimaek** [comment]
Regarding the infographic:

- We need to remove perfops completely.
- We then change the lines to show that the DNS providers route the traffic themselves without a central load-balancer
- Then we need to design and 2 new elements in the center between DNS. 1. NS1 shown as RUM data provider(aka source) 2. Our own module that pulls this data and analyzes it and then makes decisions
- Then we show lines connecting our data module to both DNS providers showing that it pushes decision data to them directly

@MartinKolarik What do you think? I can ask the designer to update it if you agree on this logic

**Comment by MartinKolarik** [comment]
He can try... the source file is here: https://www.dropbox.com/s/iqiq7podr3erzfi/infographics%20v2.psd?dl=0

I'm also not sure if our origin locations are up to date, and we're planning to switch from Amazon to DO soon, so these things should be updated as well.

**Comment by jimaek** [comment]
New files attached
[infographic.zip](https://github.com/jsdelivr/www.jsdelivr.com/files/4635960/infographic.zip)

**Comment by MartinKolarik** [comment]
Should be exported as png, not jpeg.
