### ISSUE TITLE
Marketing: Who is using jsDelivr

### ISSUE THREAD

**Issue by hubdotcom** [jsdelivr/www.jsdelivr.com#32]
NBC uses jsDelivr - we need to use these brands to show developers that large companies trust jsDelivr and they should too!

In the style of http://redis.io/topics/whos-using-redis

Data from builtwith.com of the top 20 sites (sorted by Quantcast) using jsDelivr

| Domain | Location on Site | Quantcast | Alexa | First Detected | Last Found |
| --- | --- | --- | --- | --- | --- |
| urbandictionary.com | urbandictionary.com | 40 | 499 | 1/16/14 | 4/13/15 |
| nbcnews.com | nbcnews.com | 45 | 544 | 8/6/14 | 4/13/15 |
| zillow.com | zillow.com/* | 143 | 188 | 10/12/14 | 4/13/15 |
| radaronline.com | radaronline.com | 163 | 3549 | 4/13/15 | 4/13/15 |
| rottentomatoes.com | rottentomatoes.com | 204 | 574 | 9/24/14 | 4/13/15 |
| washingtontimes.com | washingtontimes.com | 280 | 3398 | 8/6/14 | 4/13/15 |
| viralnova.com | viralnova.com | 300 | 1037 | 4/1/15 | 4/13/15 |
| rantsports.com | rantsports.com/* | 442 | 3406 | 1/27/15 | 4/13/15 |
| indiegogo.com | blog.indiegogo.com;go.indiegogo.com/*;go.indiegogo.com | 452 | 872 | 4/13/15 | 4/13/15 |
| stltoday.com | stltoday.com | 455 | 4867 | 12/24/14 | 4/13/15 |
| ajc.com | ajc.com | 495 | 4325 | 3/31/15 | 4/13/15 |
| whosay.com | whosay.com | 822 | 14650 | 4/18/14 | 3/24/15 |
| sprint.com | futureofwork.sprint.com | 869 | 1350 | 2/25/15 | 3/24/15 |
| blacksportsonline.com | blacksportsonline.com | 964 | 31101 | 1/14/15 | 3/23/15 |
| cvent.com | cvent.com/* | 985 | 4036 | 7/17/14 | 3/24/15 |
| philly.com | philly.com | 1111 | 2305 | 2/18/15 | 4/13/15 |
| youmail.com | support.youmail.com/* | 1160 | 10375 | 3/31/15 | 4/13/15 |
| thestreet.com | thestreet.com | 1173 | 2858 | 5/30/14 | 4/13/15 |
| boston.com | boston.com/* | 1639 | 1928 | 2/16/15 | 2/16/15 |
| freeshipping.com | blog.freeshipping.com | 2004 | 35519 | 3/4/15 | 4/13/15 |

**Comment by jimaek** [comment]
Good idea

**Comment by MartinKolarik** [comment]
:-1:

**Comment by hubdotcom** [comment]
I saw somewhere marketing was a challenge for jsDelivr and I agree. The platform has much potential to be realised.

How about repurposing the top header to give credibility by showing some of the organizations using jsDelivr. The old saying goes 'no one ever got fired buying IBM' - developers will trust a provider if they see others are so this could be the key to taking it from the enthusiast market to mainstream.

![Mockup](https://cloud.githubusercontent.com/assets/5274747/7145890/ac884964-e2ef-11e4-8d1a-2843a6c0ad63.png)

**Comment by MartinKolarik** [comment]
IIRC having logos of MaxCDN, Cloudflare, and Cedexis in the header was part of the deal, so I'm not sure this is possible. However, I think adding "powered by" (so that it's immediately clear what's the relationship of these companies to jsDelivr) would work equally well, since many big organizations use these CDNs.

**Comment by MartinKolarik** [comment]
This will be included in the new design.
