### ISSUE TITLE
Going live...

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#35]
Preview of the new website is available at http://beta-jsdelivr-com.herokuapp.com/. Here's a list of things we need to do before going live (@jimaek feel free to edit if I miss something).

Pages:
- [ ] WordPress CDN
- [x] Statistics
- [x] About

Other front-end tasks:
- [x] Sync collection with localStorage
- [x] Test "responsiveness", especially on mobile

Back-end:
- [x] API for stats
- [x] API for the contact form (custom sponsor)
- [ ] Edit [this script](https://github.com/algolia/wordpress-search/blob/master/import/run) so that it also saves a list of files for each plugin
- [x] Find out what's the best way to keep the index in sync with the API (@megawac ?)
- [x] Server side rendering for bots (+ support for old URL format if needed)

I'll update the list if I think of anything else. Any help, especially with the back-end tasks, is welcome.

**Comment by jimaek** [comment]
The red menu must become sticky when scrolling on all pages. Example http://lirancohen.github.io/stickUp/

Same thing when doing a search

**Comment by as-com** [comment]
It doesn't look very responsive to me...
![img_2591](https://cloud.githubusercontent.com/assets/3819625/8445443/543ef62a-1f5a-11e5-8f63-90dfd9a2d34c.PNG)

Scrolling/interacting also feels pretty slow on my iPhone 4. Perhaps the JS could be optimized a bit?

**Comment by MartinKolarik** [comment]
@as-com if you mean the overlapping logo and menu, yes, I know about that. Note that the whole site will be responsive down to 1024px only, so you'll still need to zoom on iPhone.

>Scrolling/interacting also feels pretty slow on my iPhone 4. Perhaps the JS could be optimized a bit?

Maybe yes, I'll certainly test it.

@jimaek 
>Fonts and icons are too small

Ah, good catch.

**Comment by as-com** [comment]
Here's a video of the slowness on my iPhone 4: https://youtu.be/K1mSisrRCx0

**Comment by MartinKolarik** [comment]
@as-com what kind of connection were you testing this on? Load time will certainly improve, but for search speed, it looks the bottle neck was loading the data.

**Comment by MartinKolarik** [comment]
I just tested it on my iPad using 10 Mbps wifi and the page loaded under one second and searching was almost instant.

**Comment by as-com** [comment]
30 Mbps wifi. The iPhone 4 is always very very slow at doing things. An
iPad 3 on the same network loaded the page/search results pretty quickly,
so it should be a CPU-bound issue.

(Note that I use a number of old/slow devices and like things to be energy
efficient, so I may have a different perspective than most people. :-P)

**Comment by tomByrer** [comment]
+ popup text when hovering over GUI buttons and switches please.

**Comment by jimaek** [comment]
@MartinKolarik Here is a sample data json for the stats  https://gist.githubusercontent.com/jimaek/c40ae1895f12251726d4/raw/fca1fae930ae3d82d93828f5314a4c2511ec64cf/gistfile1.json
Will this work? You would have to pull it from my server on the backend and cache it, and then output the data in a way that it wont generate a huge load on the browser.

Its missing the CDN charts because CloudFlare doesnt provide any information about hits per date, only in total for 1 month. I guess we cant add them now

**Comment by MartinKolarik** [comment]
@jimaek where do I get the real data?

**Comment by MartinKolarik** [comment]
@tomByrer added for buttons, I don't think it's necessary for switches.

**Comment by jimaek** [comment]
@MartinKolarik Here http://dev.dakulov.com/jsdelivr/stats.php until you confirm its good to go, then I will move it to an other server. (it can take a few minutes to generate the output, some APIs are VERY slow). Thats why we should cache the data and request it maybe once per hour. Also if the script fails to generate valid json we should keep the cached data.

**Comment by megawac** [comment]
I should be able to add that functionality to `/api` in 2 weeks

**Comment by jimaek** [comment]
@megawac This is the one you voted against adding to the API. Its not the per project reporting. So I guess it will remain in PHP on my server.

**Comment by jimaek** [comment]
The app keeps crashing after a while. Here are the errors https://gist.github.com/jimaek/958b1ab18efa210c0668
