### ISSUE TITLE
Add cache control headers for favicon.ico

### ISSUE THREAD

**Issue by XhmikosR** [jsdelivr/www.jsdelivr.com#350]
Maybe 1 week is enough, but right now there isn't a header at all.

Also, AFAICT favicon.ico can be served compressed, at least that's what I have noticed Cloudflare doing. Right now it doesn't make a huge diff, but if/when #342 lands it should help :)

**Comment by MartinKolarik** [comment]
It's already served with `Cache-Control: public, max-age=86400`
