### ISSUE TITLE
Switch to brotli compression

### ISSUE THREAD

**Issue by XhmikosR** [jsdelivr/www.jsdelivr.com#352]
compression 4.0.0 added support for Brotli https://github.com/koajs/compress/blob/master/HISTORY.md#400--2020-04-27

See also https://github.com/koajs/compress/issues/121

**Comment by BirkhoffLee** [comment]
We have Cloudflare in front of the site - we can just enable it from there. What do you think @jimaek

**Comment by jimaek** [comment]
I don't want to use cloudflare on the site. If they go down our CDN will work but people will think we are down because our site is down

**Comment by BirkhoffLee** [comment]
Makes sense. Would there be any downside or disadvantages if we enable Brotli in Koa? If not, I can work on the PR.

**Comment by MartinKolarik** [comment]
This is actually already enabled.
