### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#36]
- [ ] Team members: http://beta-jsdelivr-com.herokuapp.com/about#team
- [x] Adding a library (or do we just remove the 3rd paragraph?): http://beta-jsdelivr-com.herokuapp.com/free-open-source-cdn/javascript-cdn
- [x] CDN in Asia and China: http://beta-jsdelivr-com.herokuapp.com/features/cdn-in-asia-and-china
- [x] Missing sponsor descriptions

**Comment by jimaek** [comment]
* Dmitriy Akulov. Twitter `@jimaek`, Github @jimaek, Linkedin https://ua.linkedin.com/in/dakulov
* Graeme Yeates @megawac please add the social info you want to be public on the website
* Patrick Nommensen @pnommensen please add the social info you want to be public on the website
* Martin Kolárik (please add the social info you want to be public on the website)
* Austin Brown @UnbounDev please add the social info you want to be public on the website
* Andrew Sun @as-com please add the social info you want to be public on the website

(sorry if I missed anyone, ping me if you want to get added)

For avatars we can use Github as the source.

@bebraw Hey, you are no longer active but you did a lot for the project. If you want we can list you on the website as a permanent team member :)

If anyone doesn't want to be on the website then just say so.

**Comment by bebraw** [comment]
@jimaek Sure. If you want, please link to my [free book about Webpack and React](http://survivejs.com/).

**Comment by jimaek** [comment]
> Adding a library

Yes, remove that paragraph. We already have the button everywhere

> CDN in Asia and China:

Here is a rough text, someone will need to re-check all the copy on the website and improve it because I suck.

jsDelivr has partnered up with multiple Chinese companies to provide fast and reliable file delivery in China mainland and the whole Asia. We have servers inside China that improves the delivery speeds and latency significantly. Check our network map for the full list of locations.
We also have a valid ICP license issued by the Chinese government that protects us from bans and other issues.

**Comment by MartinKolarik** [comment]
@jimaek two more things: some sponsors don't have descriptions, and we should probably add KeyCDN to multi-cdn section of features.

**Comment by jimaek** [comment]
Yes, lets add the missing CDNs to the Multi-CDN part.

**CloudFlare**:
Main backend CDN for jsDelivr offering unlimited bandwidth and locations.
"Offers free and commercial, cloud-based services to help secure and accelerate websites."

**MaxCDN:** (needs a new logo https://github.com/MaxCDN/media/blob/master/Logos/MaxCDN/MaxCDN-Orange-Vector.pdf)
Main backend CDN for jsDelivr offering unlimited bandwidth and locations.
"Make your websites and apps faster, purge and provision content instantly, and get CDN analytics in real time."

**KeyCDN:**
Main backend CDN for jsDelivr offering unlimited bandwidth and locations.
"KeyCDN is a high performance Content Delivery Network (CDN). Our global delivery network instantly speed up your websites, online games or live streams."

**NSONE:**
Our exclusive DNS hosting provider offering unlimited DNS queries and an additional layer of failover.
"Industry leading DNS traffic management - managed DNS, private DNS networks, and powerful turnkey traffic routing setups."

**Comment by megawac** [comment]
Sure can you just add a link to my github account and twitter (https://twitter.com/GraemeYeates)

**Comment by UnbounDev** [comment]
A link to github and linkedIn would be perfect: https://github.com/UnbounDev && www.linkedin.com/in/austinjbrown (preference given to linkedIn if there's only room for one link).

**Comment by pnommensen** [comment]
Twitter: https://twitter.com/pnommensen
LinkedIn: https://linkedin.com/in/pnommensen

thanks.

**Comment by jimaek** [comment]
**Cedexis**:
Our smart load-balancing engine that performs real time performance monitoring and load balancing based on RUM and uptime data. 
"Optimize clouds, data centers and CDN content delivery to improve the availability, latency and throughput of your website and mobile apps, for every user on the globe. "

**Algolia**
Algolia Search provides hosted full-text, numerical, faceted and geolocalized search.

**Comment by MartinKolarik** [comment]
@as-com any link you'd like to have on the website?

**Comment by as-com** [comment]
@martinkolarik Not right now. I might need to clean up my server so it can handle the load. Perhaps you can add it later?

**Comment by MartinKolarik** [comment]
>Perhaps you can add it later?

Sure, just ping me when you want to add it.

**Comment by jimaek** [comment]
@MartinKolarik A small bug http://lb.jimaek.svc.tutum.io/about

1. Click right to open the last member
2. Click left to go to beginning and "Graeme" becomes first, I am not there anymore and need to refresh to see myself

**Comment by MartinKolarik** [comment]
@jimaek what browser and OS? I've just tested it in Chrome, Firefox, and IE and couldn't reproduce it.

**Comment by jimaek** [comment]
Firefox, windows 10. Same things happens with the last person too. Sometimes I can see myself but cant see the last person. Not sure how to reproduce. I simply click left and right a lot of times

**Comment by jimaek** [comment]
Maybe its best to just show them in 2 rows without any navigation? Simple and no bugs :)

**Comment by MartinKolarik** [comment]
Nah, I found it. Should be OK now.
