### ISSUE TITLE
Make Copy button not use flash when necessary

### ISSUE THREAD

**Issue by as-com** [jsdelivr/www.jsdelivr.com#37]
Users with Flash Player blocked/blacklisted/click-to-play/disabled/not installed should be able to use the copy button via this [new method](https://developers.google.com/web/updates/2015/04/cut-and-copy-commands?hl=en).

GitHub's copy buttons no longer use flash. We should do the same.

**Comment by MartinKolarik** [comment]
:+1: I wanted to look into this. Should be easy to use this with flash as a fallback.

**Comment by tomByrer** [comment]
Yes, I use a Flash blocker as well.
