### ISSUE TITLE
Handle deprecated versions better (remove/mark them)

### ISSUE THREAD

**Issue by wojciechczerniak** [jsdelivr/www.jsdelivr.com#370]
**Is your feature request related to a problem? Please describe.**
When we deprecate a version that is broken it's still available through jsdelivr

**Describe the solution you'd like**
Do not display deprecated versions in the dropdown at all. Redirect those version or 404 them. NPM will display the message on `npm install`, here there is no other way to warn the user about broken build.

**Describe alternatives you've considered**
Mark the version as deprecated. Display the message as `npmjs` does it.

**Additional context**
A deprecated version: https://www.npmjs.com/package/handsontable/v/7.4.1
Available at jsdelivr: https://www.jsdelivr.com/package/npm/handsontable?version=7.4.1

**Comment by MartinKolarik** [comment]
We display a deprecation warning for packages that were deprecated as a whole, but don't have that information for individual versions right now. It should be discussed at https://github.com/algolia/npm-search and if it's added to the index, we can show the warning here.

**Comment by wojciechczerniak** [comment]
> > When we deprecate a version that is broken it's still available through jsdelivr
> 
> Although the version of a package has been deprecated, there might be some website start using it. A deprecated version might have few bugs, but return `404` will break those websites _completely_.

Good point. I didn't took under consideration a version that was online longer than few minutes. 404 is a very bad idea.

**Comment by MartinKolarik** [comment]
Of course, anything we do here would only affect the website, not the actual availability of the files at the CDN. That's why I moved the issue here.

**Comment by MartinKolarik** [comment]
The thing to do here is opening an issue the linked Algolia repo, describing the need to track the deprecation of individual versions, then sending them a PR. After the PR is merged there, our website can be updated to show the warning. @MattMarquise let me know if you'd like to handle this.

**Comment by jimaek** [comment]
Closing for now as it relies mostly on Algolia
