### ISSUE TITLE
Handle unpublished packages

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#371]
https://registry.npmjs.cf/mbdocsify-sidebarfooter

Right now, we show them in [search results](https://www.jsdelivr.com/?query=mbdocsify-sidebarfooter) but the package page [doesn't load](https://www.jsdelivr.com/package/npm/mbdocsify-sidebarfooter). We should probably hide them from search.

**Comment by xbpcb** [comment]
@MartinKolarik  It seems impossible to tell if the package is published or not  relying on the available attributesToRetrieve. According to the algoliasearch response to get specific package the package is exists but attempt to get the package from the data.jsdelivr.com leads to 404. What do you think, am i missed some approach?

**Comment by MartinKolarik** [comment]
Yes, it's possible this would need changes in https://github.com/algolia/npm-search first.

**Comment by MartinKolarik** [comment]
A fix for this was included in our recent search changes.
