### ISSUE TITLE
Link migration pages in footer

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#376]
Has this been linked anywhere yet? This is such a useful feature of other CDNs, is there any reason it's not already linked on the homepage under the GitHub documentation?

_Originally posted by @mattrossman in https://github.com/jsdelivr/www.jsdelivr.com/issues/270#issuecomment-747756472_

**Comment by MartinKolarik** [comment]
A separate row in the footer, below `© jsdelivr.com, 2012 - 2021  About  Terms & Policies  dak@prospectone.io` in the following form:

Migrating from: GitHub &nbsp; Google Hosted Libraries &nbsp; RawGit &nbsp; unpkg

Each service name links to the appropriate page and the style/spacing is the same as in the row above.

**Comment by jimaek** [comment]
Maybe under the tools menu in nav?

**Comment by MartinKolarik** [comment]
Might work too, would you say both nav and footer or only footer?

**Comment by jimaek** [comment]
Maybe both, and in tools probably makes sense to have a submenu. Tools -> Migration -> Google, Github...

**Comment by MartinKolarik** [comment]
bootstrap doesn't support submenus out of the box so I'd stick with a simple list for now. All the "Migrate from X" then a horizontal line separator and then the current two entries.
