### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#38]
The website needs to be fast.

Current problems:
 - [x] All pages load stats related resources.
 - [x] `/css/app.min.css.map` gets loaded 7 times on the homepage
 - [x] Memory leak https://gist.githubusercontent.com/jimaek/e79070185effe02854e0/raw/7380acf74fd4147a2d1fff00f06f399ec4e4be42/gistfile1.txt
 - [x] phantomjs is a huge recourse hog
 - [x] App is slow to start. From the beginning of `npm start` until its ready to serve HTTP requests

Features:
 - [x] Server-side rendering (only for bots or users too? Why not?)
 - [x] CDN the whole website http://www-jsdelivr-com.dak.netdna-cdn.com/
 - [x] Respond with 304 instead of 200 when appropriate. (only header, no content)

**Comment by MartinKolarik** [comment]
>/css/app.min.css.map gets loaded 7 times on the homepage

`.map` files are only loaded with devtools open

>phantomjs is a huge recourse hog

Yes, but I don't think there's much we can do about it. Generating the images we need should take only a couple of seconds every hour though.

>Server-side rendering (only for bots or users too? Why not?)

I didn't want to use it for regular users because Ractive is rather slow on server, but if the responses are cached on CDN, then there's most likely no problem.

**Comment by MartinKolarik** [comment]
>Respond with 304 instead of 200 when appropriate. (only header, no content)

This should already work.

**Comment by jimaek** [comment]
>    Respond with 304 instead of 200 when appropriate. (only header, no content)
>
>This should already work.

Doesnt seem to be working https://dl.dropboxusercontent.com/s/99uoe9b5ae6zyzc/2015-07-19_18-58-44.png?dl=0

**Comment by MartinKolarik** [comment]
Closing as all issues should be resolved. @jimaek reopen if there's anything more.
