### ISSUE TITLE
test at various browser widths

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/www.jsdelivr.com#39]
Every view.
For example, the word wrap of the smaller font could be improved:
![jsdelivr_narrow](https://cloud.githubusercontent.com/assets/1308419/8896788/fb93b1fe-33c3-11e5-98b1-175bf5ed2997.png)

**Comment by jimaek** [comment]
The site was built for desktops and laptops. Making it work on smartphones didnt make sense and it was too expensive. From the screenshot it looks like a smartphone size so unless someone wants to fix it himself there is not much I can do :(

**Comment by MartinKolarik** [comment]
The site was designed for large screens (1900px+). I did what I considered reasonable amount of work to make it responsive down to 1024px as that should be enough for all laptops and most tablets. This particular thing was rather easy to fix, so I did, but the priority (at the screen size) is that it works.

**Comment by tomByrer** [comment]
Thanks for the fix.

BTW, my laptop screen is 1920x1080px, & I **NEVER** view the web at full screen width unless the website forces me to.  I keep editors, CLI, & browser open at the same time, & prefer to have at least 2 of them viewable on the screen at the same time, so their windows are 1/3 to 2/3 of the screen width..  & I'm sure I'm not the only dev who does this (noting the devs I've seen at Pivotal Labs, Yahoo, MapQuest, etc).

**Comment by jimaek** [comment]
I see, as I understand its fixed now?

@MartinKolarik Thank you for the fix!

**Comment by tomByrer** [comment]
Seems to be fixed, ty.
