### ISSUE TITLE
Optimize resources usage

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#390]
The site is using an unreasonable amount of RAM and CPU.
For such a small site and all data coming from external sources it doesn't make sense I think.

We should look into this and try to optimize everything to lower the load especially on traffic spikes

**Comment by MartinKolarik** [comment]
At 100 requests per second, it is going to use some resources and we can easily get 200 or 300 per second sometimes. We absolutely should keep using CF and then there's no issue.

**Comment by jimaek** [comment]
It's not that many for a site like this where there is basically no data manipulation on the backend.
I would expect it to handle that amount with under 2GB of RAM.

Maybe there are leaks somewhere and we could also enable some local caching

**Comment by MartinKolarik** [comment]
It's not about RAM as much as CPU. If the dynamic rendering takes, let's say, 20 ms, then you get 50 r/s with one core. Above that, the requests start piling up, which eats the RAM. It needs a caching layer on top, and that layer was the CDN. We could use an nginx in front, or implement additional caching here but there's no point because the CDN will always perform better.

**Comment by jimaek** [comment]
I kind of disagree, my point is that either we're doing something wrong or we are using the wrong tools.
It should be able to handle it without Cloudflare and piling up.

An example would be switching to Fastify https://github.com/fastify/fastify#benchmarks or looking into other solutions

**Comment by MartinKolarik** [comment]
As I said, we just need a caching layer, and there are multiple ways to add it. Other than that, we're not doing anything wrong. But even if we did our own caching and managed to handle 500 r/s, we should still keep the CDN - that's my point here.

The fastlify benchmark shows the performance of an app that does literally nothing - and even that on a large server. It's not relevant here.

**Comment by jimaek** [comment]
https://github.com/jsdelivr/www.jsdelivr.com/issues/462
