### ISSUE TITLE
Add custom endpoint pages

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#399]
One page listing all of them, the one page for each project (data specified in the config). Should include:

 - The endpoint name, short description
 - Links to external docs, if any
 - Stats: we have hits/bandwith now (this would be the main content)

**Comment by jimaek** [comment]
This is not enough description to design the page, can explain a bit more what needs to be there and the exact content to provide it to the designer?

**Comment by MartinKolarik** [comment]
CocoaPods

CocoaPods is a dependency manager for Swift and Objective-C Cocoa projects. It has over 87 thousand libraries and is used in over 3 million apps. CocoaPods can help you scale your projects elegantly.

https://cocoapods.org/


Pyodide

Pyodide brings the Python 3.9 runtime to the browser via WebAssembly, thanks to Emscripten. It builds the Python scientific stack including NumPy, Pandas, Matplotlib, SciPy, and scikit-learn. Over 75 packages are currently available. In addition, it’s possible to install pure Python wheels from PyPI.

https://pyodide.org/


MuseScore

Create, play and print beautiful sheet music. The world’s most popular notation software.

https://musescore.org/


Stats: number of requests and bandwidth - we have daily data for both. We should probably show a bar chart and similarly to the package page, have a switch between requests/bandwidth and a date grouping dropdown.

-----

Alternative version: Instead of having a separate chart for each project, just show the monthly total for requests and bandwidth. Open a chart after clicking on a button.

**Comment by MartinKolarik** [comment]
+ there should be a call to action to request an endpoint and some text. Here's what we have on GH currently:

Custom CDN Hosting
We can work together and setup a custom configuration for your project. This way, you can have full control over your files and the ability to utilize the full power of jsDelivr.

This kind of custom hosting can be suitable for:

Binary hosting. Windows executable files and zips.
Frequently updated files.
Projects that can't follow jsDelivr file structure.
Some other use that will blow all of our minds.
Simply send an email to dak@prospectone.io with a request for more information.

**Comment by jimaek** [comment]
Added in new design
