### ISSUE TITLE
Recheck image sizes

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#406]
After #351 we've got wrong dimensions set in some places. I noticed and fixed one in 4ba9170e9a4174f4cc2a695e978c2ea75acd39d7, now noticed another one at https://www.jsdelivr.com/esm (our logo looks bad). @xbpcb please recheck all images in all places and fix the ones that are wrong.

**Comment by xbpcb** [comment]
I am not sure about this https://github.com/jsdelivr/www.jsdelivr.com/commit/4ba9170e9a4174f4cc2a695e978c2ea75acd39d7
The correct width of google logo is 154px
Check it:
![2021-09-04_14-11](https://user-images.githubusercontent.com/13244319/132092447-e1145291-ff16-4bc9-bf11-0d69e9eb544d.png)
![2021-09-04_14-12](https://user-images.githubusercontent.com/13244319/132092450-121613c4-9c9a-40cf-945e-cb304e583161.png)

**Comment by MartinKolarik** [comment]
I see the problem now - we don't have the same aspect ratios for the regular and @2x version. You set the dimensions for the regular version and it looked broken when I got the @2x version displayed.

So need to check and fix the images - Google, our logo on these pages, and anything else that you find.

**Comment by MartinKolarik** [comment]
Another thing that has a wrong size is the hits badge at https://www.jsdelivr.com/package/npm/bootstrap - the width can't be set as it changes depending on the content.

**Comment by MartinKolarik** [comment]
@xbpcb please prioritize this issue.

**Comment by xbpcb** [comment]
@MartinKolarik  got it
