### ISSUE TITLE
Add history page

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#408]
- starting from 2012 list the most important events like getting big sponsors, usage milestones, key features, and project acquisitions (most can likely be picked from our Twitter timeline)
 - should ideally be HTML for easy editing but visually it should look like an infographic, not just simple text
 - link in the footer and a banner in About us and/or homepage

**Comment by jimaek** [comment]
Content for designer to use, (not accurate and random dates, just to make it clear how much stuff he needs to put):

- June 2012 Founded by Dmitriy Akulov
- August 2012 MaxCDN joins as sponsor
- October 2012 Cloudflare joins as sponsor
- November 2012 Cedexis joins as sponsor and makes multi-CDN official
- December 2012 10 billion monthly requests
- June 2013 first redesign
- May 2014 Fastly joins as sponsor
- October 2014 /g/ combination feature is launched
- October 2015 Martin Kolarik joins as core developer
- January 2016 50 billion monthly requests
- November 2016 Quantil joins as sponsor
- December 2016 jsDelivr gets Chinese ICP license
- January 2017 updates are automated using a bot
- March 2019 NPM and Github support is launched with old github commits workflow sunset
- June 2020 detailed download stats are launched 
- May 2021 Rawgit switches to jsDelivr
- July 2021 BootstrapCDN joined
- August 2021 131 billion monthly requests



(edit comment as needed)

**Comment by MartinKolarik** [comment]
To make adding new events easy, the graphic elements should probably repeat for the same kind of event, e.g., "new sponsor" would have a specific icon/set of elements, "new feature" can look different but be the same for all features...

**Comment by MartinKolarik** [comment]
Good, I think the list is final then.

**Comment by jimaek** [comment]
Its more or less done, small fixes can be done directly in the branch.
