### ISSUE TITLE
https by default?

### ISSUE THREAD

**Issue by ajkj** [jsdelivr/www.jsdelivr.com#41]
what do you think of showing https URL ( https://cdn.jsdelivr.net/path/to/file ) by default rather than showing protocol less URL ( //cdn.jsdelivr.net/path/to/file ).

encouraging using https could maximize cache effect.
and spdy3.1/http2(on firefox) works only on https

**Comment by MartinKolarik** [comment]
I think it's a good idea in this case.

**Comment by pnommensen** [comment]
+1 http://www.paulirish.com/2010/the-protocol-relative-url/ 

The protocol relative URL is an anti-pattern.
