### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by Ei-aaie** [jsdelivr/www.jsdelivr.com#437]
[This package](https://www.jsdelivr.com/package/npm/@maltjoy/tokens) was not found on jsDelivr CDN, but it should have been.

Same for : 
[This package](https://www.jsdelivr.com/package/npm/@maltjoy/core) was not found on jsDelivr CDN, but it should have been.

It used to work for weeks though

**Comment by jimaek** [comment]
We have opened an issue about this with Algolia, its not something we can influence directly ourselves. Our index comes from Algolia https://github.com/algolia/npm-search/issues/930
