### ISSUE TITLE
Issues in redesign

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#438]
GitHub is hiding comments in #400 because there are too many, so we're going to track all remaining issues here for better visibility.

**Comment by MartinKolarik** [comment]
Package page: https://www-jsdelivr-com-pr-400.onrender.com/package/npm/react
 - [x] `undefined` chart labels on Statistics tab - be sure to test all period options including yearly
   - [ ] the fix for this broke charts in the sidebar (compare with design)
   
![image](https://user-images.githubusercontent.com/6192491/170256108-a5552eeb-1e40-4a86-b278-f6cebd104955.png)

 - [x] chart labels on Y axis - number should be aligned to the right and have space between every three digits (see design), use `_.formatNumber`
   - [ ] still no space between digits and broke formatting:
![image](https://user-images.githubusercontent.com/6192491/170256433-1f219dcb-f9c1-43e3-ab2e-756d322134d8.png)

 - [ ] "Group by" - this needs to be implemented on the client. Show only the groups for which we have all the data, drop the first/last group with partial data. Example: today is May 13, I select yearly range and group by month. Data for May won't be shown because the month isn't complete yet, the chart will have (from right to left) April, March, ..., until June 2021 (again May 2021 won't be shown because the API response will only have data for dates 13. 05. 2021 - 31. 05. 2021). 
 - [ ] the version text should not change color on open - still wrong when you open it and hover something in the dropdown
![image](https://user-images.githubusercontent.com/6192491/168244532-858279f4-2e86-45df-9216-404e9f373396.png)

Fixed:

<details>

 - [x] if a package doesn't have a readme, show the "Show/Configure Files" tab on load (https://www-jsdelivr-com-pr-400.onrender.com/package/npm/yandex-metrica-watch)
 - [x] Ignore "day" period for charts - if a user selects "day", don't update the charts, keep whatever was shown before, update only the tables (see how it works at https://www.jsdelivr.com/package/npm/react)
 - [x] Vulnerabilities badge needs to be a link (see at master branch)
 - [x] code/icon overlap 
![image](https://user-images.githubusercontent.com/6192491/168694027-e4518e81-6764-47e7-9f1e-0394e4772135.png)

</details>

**Comment by MartinKolarik** [comment]
All pages:
 - [ ] In all places where we refer to "requests" and "GB", it should be "requests" and "bandwidth" and the unit should be part of the value. E.g. this switch but it's in many places so use search for "GB" and fix everywhere:

![image](https://user-images.githubusercontent.com/6192491/162586832-4c47e2c7-9141-476a-a30f-343afb2062e1.png)

**Comment by jimaek** [comment]
On mobile project pages don't look good. They are positioned to the left ![Screenshot_20220526-182414](https://user-images.githubusercontent.com/1834071/170531216-e4773667-76c7-4d73-9148-84613e915585.png)

**Comment by IvanAdamovic646** [comment]
> All pages:
> 
> * [ ]  In all places where we refer to "requests" and "GB", it should be "requests" and "bandwidth" and the unit should be part of the value. E.g. this switch but it's in many places so use search for "GB" and fix everywhere:
> 
> ![image](https://user-images.githubusercontent.com/6192491/162586832-4c47e2c7-9141-476a-a30f-343afb2062e1.png)

@MartinKolarik, could you explain more about this point?
![image](https://user-images.githubusercontent.com/104014061/170541524-266e62a0-22d3-49a6-92a8-2d8cf9596ea9.png)
Does the current chart is about for "GB" ? right?

**Comment by MartinKolarik** [comment]
@IvanAdamovic646 
![image](https://user-images.githubusercontent.com/6192491/170548667-d89f7cbd-ebd8-4445-b3eb-235aad4a2565.png)

**Comment by IvanAdamovic646** [comment]
So we are fetching "Request" data using "fetchPackageDateStats" function and the api url is 
https://data.jsdelivr.com/v1/package/npm/react-is/stats/bandwidth/date/month

To get "GB" data, we can use "fetchPackageBandwidthStats" function and api url is 
https://data.jsdelivr.com/v1/package/npm/react-is/stats/bandwidth/date/month

right?

**Comment by MartinKolarik** [comment]
@IvanAdamovic646 you wrote the same URL twice but yes, the function names are correct.

**Comment by IvanAdamovic646** [comment]
Thanks for details, @MartinKolarik .

**Comment by MartinKolarik** [comment]
We now have preview endpoints for everything except part of the stats page. All data mocks should be replaced by the real endpoints.

 - [ ] Custom OSS stats: https://www-jsdelivr-com-pr-400.onrender.com/custom-cdn-oss (code https://github.com/jsdelivr/www.jsdelivr.com/blob/b75210f927f0fcfc33f53863cc980ade6cd92f09/src/views/pages/custom-cdn-oss.html#L59 and https://github.com/jsdelivr/www.jsdelivr.com/blob/e090531502551a17b602040ea94b80adf0c9cb36/src/views/components/request-bandwidth-stats.html#L59), currently uses random data from package endpoint instead of OSS CDN data (the same component is used also on package pages so it needs to work for both types - on package pages, it's already correct but when rendered from the custom cdn pages, the API endpoints are different). Correct API for custom OSS:
   - https://data-jsdelivr-com-preview.onrender.com/v1/proxy/cocoa/stats?type=hits
   - https://data-jsdelivr-com-preview.onrender.com/v1/proxy/pyodide/stats?type=hits
   - https://data-jsdelivr-com-preview.onrender.com/v1/proxy/musescore/stats?type=hits
   - https://data-jsdelivr-com-preview.onrender.com/v1/proxy/cocoa/stats?type=bandwidth
   - https://data-jsdelivr-com-preview.onrender.com/v1/proxy/pyodide/stats?type=bandwidth
   - https://data-jsdelivr-com-preview.onrender.com/v1/proxy/musescore/stats?type=bandwidth
   - [ ] same on the details page: https://www-jsdelivr-com-pr-400.onrender.com/custom-cdn-oss/cocoapods

**Comment by MartinKolarik** [comment]
Homepage:
 - [ ] try to make the bars a little smaller to that we at least fit the numbers in one line (name can stay in two lines, not much we can do about that) 
https://user-images.githubusercontent.com/6192491/171481738-1443b17c-c217-4e1c-b4af-062a12f9ab05.png
 - [ ] the footer is in a broken state at exactly 767px width 
https://user-images.githubusercontent.com/6192491/171481994-b5321a82-8cc8-41a4-8022-0e0f40027af3.png
 - [ ] use two columns here so that it's aligned with the part below (on smaller width it's correctly) 
https://user-images.githubusercontent.com/6192491/171482637-544420d9-d765-4543-a0a9-36af565ce5a3.png
 - [ ] open menu must be full width (probably issue with some bootstrap var?) 
https://user-images.githubusercontent.com/6192491/171483027-9063a564-5342-4882-847c-39f93e5c2853.png

**Comment by IvanAdamovic646** [comment]
@MartinKolarik 
`tweet button has broken text: "jquery is the 11th most popular package on https://github.com/jsdelivr CDN, with 23 344 847 771 hits in the last year: undefined"`
Can you tell me what can be replaced instead of `undefined`?

**Comment by MartinKolarik** [comment]
> @MartinKolarik 
> `tweet button has broken text: "jquery is the 11th most popular package on https://github.com/jsdelivr CDN, with 23 344 847 771 hits in the last year: undefined"`
> Can you tell me what can be replaced instead of `undefined`?

It's supposed to be a link to that page.

**Comment by MartinKolarik** [comment]
> I'm attaching image about the link for tweet button.
> ![image](https://user-images.githubusercontent.com/104014061/172204358-4fdb2bb4-fadb-436a-9aff-a2bf33c89798.png)
> I have checked again which can be the link to that page but still not sure what can be the proper link for it.
> Could you give me a hint or proper tweet url for attached page again please?

in this case it would be the full localhost url to that page, which you see in the browser url bar (simply `location.href`)

**Comment by IvanAdamovic646** [comment]
Ok. thanks for letting me know.

**Comment by IvanAdamovic646** [comment]
@MartinKolarik 
`on smaller screens, the sidebar is cut, we should make it work down to 992px ideally and then hide it below 992 (currently it's still partially visible)`
Regarding this issue, 
currently, I have updated this page that it can work down to 1200px hiding sidebar. Let me know please if current state is okay.

Or when size down like to 995px, is it okay to split 2 line of the button text ?
![image](https://user-images.githubusercontent.com/104014061/172628905-1d30a8aa-0c65-4aeb-b126-d9c49de113f4.png)

**Comment by MartinKolarik** [comment]
@IvanAdamovic646 we could probably come up with a different layout for the buttons but generally I hoped we could make the right panel smaller on that size.

**Comment by MartinKolarik** [comment]
Stats page:
 - [ ] use the correct flags in all places (https://github.com/jsdelivr/www.jsdelivr.com/pull/400#issuecomment-1147972967)
    - [ ] add css for rounded corners
