### ISSUE TITLE
Website doesn't load

### ISSUE THREAD

**Issue by pzich** [jsdelivr/www.jsdelivr.com#439]
For the last few days whenever I try to visit https://www.jsdelivr.com/ , https://www.jsdelivr.com/esm , etc. I am greeted by a blank page. If I `curl` I see `content-length: 0`
```
$ curl -I https://www.jsdelivr.com/esm
HTTP/2 200 
date: Fri, 24 Jun 2022 21:53:48 GMT
content-length: 0
server: BunnyCDN-SIL-915
cdn-pullzone: 499836
cdn-uid: b1941f61-b576-4f40-80de-5677acb38f74
cdn-requestcountrycode: US
cdn-status: 200
cdn-requestid: f186f8c730053b0dc56b3a91ecc5b307
cdn-cache: HIT
```
I tried the same from my VPN and other servers and had the same issue.
```
$ curl -I https://www.jsdelivr.com/esm
HTTP/2 200 
date: Fri, 24 Jun 2022 22:00:42 GMT
content-length: 0
server: BunnyCDN-WA-642
cdn-pullzone: 499836
cdn-uid: b1941f61-b576-4f40-80de-5677acb38f74
cdn-requestcountrycode: US
cdn-status: 200
cdn-requestid: 7777ef187c970f054904267f59d6e098
cdn-cache: HIT
```
Is anyone else seeing this? I can work around it by adding a bogus parameter like https://www.jsdelivr.com/esm?wtf=bbq

**Comment by pzich** [comment]
Does https://status.jsdelivr.com/ not check the CDN health? Or maybe it sees the 200 but doesn't check for actual content?

<img width="1204" alt="https://status.jsdelivr.com/" src="https://user-images.githubusercontent.com/706138/175698786-fd077941-13ab-451d-a66f-0e6465897d7d.png">

**Comment by MartinKolarik** [comment]
I'm not having this issue myself and the monitoring runs in eight locations (three in the US) and checks the actual response contents 🤔

**Comment by jimaek** [comment]
@pzich Can you please check if the issue still persists?

**Comment by BaoJieBox** [comment]
This problem still exists. It has been several days. Now the website can be opened, but it looks interesting to return blank, 0 content,and I found that the server is server: bunnycdn-la-558
However, pzich, how do you know that when you add the request query parameters like "? =xxxx", the website suddenly works normally!
Pzich, you are so awesome. I love you very much because you helped me solve this annoying problem

**Comment by jimaek** [comment]
That's a strange issue, feels like some cache somewhere got stuck. I made some modifications to the CDN. Can you check again please?
