### ISSUE TITLE
Scroll to search results on the Hero Unit when the user stops typing

### ISSUE THREAD

**Issue by abishekrsrikaanth** [jsdelivr/www.jsdelivr.com#44]
**Issue:**
Current when a library is searched on the Hero Unit on the index page, it scrolls to the result only when the enter key is pressed. The current website doesn't require the user to hit enter, so should the new website as the search results are retrieved as the user types in the textbox.

**Workaround:**
Setup a debounce of keypress to identify when the user stops typing and scroll to the search results.

Including @MartinKolarik as suggested by @jimaek

**Comment by MartinKolarik** [comment]
I don't like the debounce solution. I think it'd either feel too slow, or randomly jump down if you pause typing. @jimaek we might add the button which was in the original PSD files. I thought there was no use for it as the search is instant, but scrolling down on click might be a good idea.

**Comment by jimaek** [comment]
Well it wont solve the problem @abishekrsrikaanth is describing. Currently we already have the same solution with the enter.

How about scrolling down the minute the user clicks inside the input field and automatically switch to the search input in the red nav menu?

**Comment by MartinKolarik** [comment]
>Well it wont solve the problem @abishekrsrikaanth is describing. Currently we already have the same solution with the enter.

It would solve the problem that users don't know they need to hit enter. If the button were there, they'd most likely click it.

>How about scrolling down the minute the user clicks inside the input field and automatically switch to the search input in the red nav menu?

That should work as well.
