### ISSUE TITLE
Duplicate pages with different GET parameters

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#442]
We should fix this issue for better SEO:

Some pages with GET parameters in the URL on your site https://www.jsdelivr.com duplicate the contents of other pages (without GET parameters). For example, https://example.com/tovary?from=mainpage duplicates https://example.com/tovary. Because both pages are crawled, it might take longer for the information about important pages to be added to the search database. This may affect the site's search status.

Here are examples of pages and their duplicate pages with insignificant GET parameters:

query:
https://www.jsdelivr.com/
https://www.jsdelivr.com/?query=author%3A%20deiga
query:
https://www.jsdelivr.com/
https://www.jsdelivr.com/?query=author%3A%20lord
query:
https://www.jsdelivr.com/
https://www.jsdelivr.com/?query=author%3A%20qiaoshi2
tid:
https://www.jsdelivr.com/
https://www.jsdelivr.com/?tid=221130841
tid:
https://www.jsdelivr.com/terms/privacy-policy-jsdelivr-net
https://www.jsdelivr.com/terms/privacy-policy-jsdelivr-net?tid=311824738

If these pages are duplicates, we recommend using the Clean-param directive in robots.txt, so that the robot ignores insignificant GET parameters and combines signals from identical pages on the main page.

**Comment by MartinKolarik** [comment]
Well they are not actually duplicate but maybe we could indeed ignore the search query as it doesn't seem very useful to index. We don't use the other param not sure where google got it from.
