### ISSUE TITLE
hidden sponsors if not full screen

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/www.jsdelivr.com#45]
I imagine sponsors give a lot of free stuff to jsDelivr, so their logos should be viewable when the page is initially loaded.  [I never view webpages full screen](https://github.com/jsdelivr/www.jsdelivr.com/issues/39#issuecomment-125504244).

Here is how I usually view the web in dev-mode:
![jsdelivr_desktop](https://cloud.githubusercontent.com/assets/1308419/9010909/1cb3ad3e-3767-11e5-9f72-3635f67d9b53.jpg)
& yes @jimaek, I do want to develop using my iPad; walking an hour with my small laptop hurts my back.

In general, I agree with @abishekrsrikaanth; I don't like hero layouts for sites I try to be productive with.

**Comment by jimaek** [comment]
Well there is nothing I can do here about the sponsors. Whatever I do you can always make the screen smaller. I dont think our sponsors will say anything since all you need to do to see their logo is scroll down.

**Comment by tomByrer** [comment]
I was thinking the sponsors should be closer to top.

BTW, does anyone have stats (eg Google Analytics) on current jsdelivr.com browser sizes?

**Comment by jimaek** [comment]
Maybe we could cut some of the empty space. Not sure if it would look good though.

Size stats https://dl.dropboxusercontent.com/s/p41kil6ekspsh87/2015-07-31_21-35-26.png?dl=0

**Comment by tomByrer** [comment]
Thanks for the stats.  Is that *browser window* size, or screen size?

**Comment by jimaek** [comment]
I dont think Google analytics reports the actual browser window size. If you find a way then let me know.
