### ISSUE TITLE
Add Ghost page

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#457]
Add to:
 - https://www-jsdelivr-com-pr-400.onrender.com/custom-cdn-oss
 - https://www-jsdelivr-com-pr-400.onrender.com/custom-cdn-oss/ghost

website: https://ghost.org/
docs: https://ghost.org/docs/install/
stats api: https://data-jsdelivr-com-preview.onrender.com/v1/stats/proxies/ghost

text: Ghost is a powerful app for new-media creators to publish, share, and grow a business around their content. It comes with modern tools to build a website, publish content, send newsletters & offer paid subscriptions to members.

**Comment by xbpcb** [comment]
PR #475
