### ISSUE TITLE
Third-party images and badges in readmes

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#465]
In order to keep Google happy and optimize the performance of our project pages I made a serverless image proxy and optimizer on top of Gcore. There is no origin at all and all sources must be manually pre-approved:

Current supported domains I took from popular readmes:
https://img.jsdelivr.com/cloud.githubusercontent.com/assets/835857/14581711/ba623018-0436-11e6-8fce-d2ccd4d379c9.gif
https://img.jsdelivr.com/img.shields.io/badge/code_style-standard-brightgreen.svg
https://img.jsdelivr.com/raw.githubusercontent.com/wiki/js-cookie/js-cookie/Browserstack-logo%402x.png
https://img.jsdelivr.com/github.com/jquery.png?s=20
https://img.jsdelivr.com/upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Canal%2B.svg/2000px-Canal%2B.svg.png
https://img.jsdelivr.com/opencollective.com/bootstrap/sponsor/0/avatar.svg
https://img.jsdelivr.com/flat.badgen.net/circleci/github/nuxt-community/workbox-cdn
https://img.jsdelivr.com/images.opencollective.com/casinofiables-com/b824bab/logo.png
https://img.jsdelivr.com/avatars.githubusercontent.com/u/9919?v=4&s=128
https://img.jsdelivr.com/badgen.net/github/checks/pillarjs/router/master?label=ci

_Originally posted by @jimaek in https://github.com/jsdelivr/www.jsdelivr.com/issues/462#issuecomment-1282432018_

**Comment by MartinKolarik** [comment]
> all sources must be manually pre-approved

That makes it hardly usable for this purpose unless we hardcode a list of domains to rewrite and keep the others without change.
