### ISSUE TITLE
Homepage bugs

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#467]
- [x] ESM docs missing
- [x] gcore sponsor must point to gcore.com
- [x] "Four CDN & two DNS providers" must point to infographic
- [x] "Low latency "Near China"network" must point to the China section on network oage
- [x] "Smart load-balancing..." must point here /documentation#id-multi-cdn
- [x] "Formal tos..." must point here /terms
- [x] Top animations dont start from 0 for some reason. Maybe they should?
- [x] The requests per second and mbps numbers should be accurate and based on total hits value reported by API
- [x] Round Mbps value to avoid decimals
- [x] The real-time stats animation is laggy and weird. There are big delays and its not consistent. Looks strange
- [ ] Not sure if related to above, but scrolling the homepage is laggy and feels slow
- [x] All links in "Developer Friendly" section need hover styles
- [x] Most links in "Developer Friendly" section are broken, please review and fix
- [x] Remove a line from second tab to avoid the pointless scroll https://dl.dropboxusercontent.com/s/cbsdblpeqn2qwjn/chrome_2022-11-05_18-50-21.png
- [x] #495
- [x] The ESM demo is not working
- [x] Wrong font weight in stats? https://dl.dropboxusercontent.com/s/3mloix2wvcljcrq/chrome_2022-11-05_18-51-29.png
- [x] When search is open if the user clicks on the logo it should reset the state to normal non-search homepage
- [x] When homepage is opened and user stats typing it should scroll down to the input, which it does, but it should do it even lower to fit some results https://dl.dropboxusercontent.com/s/fm8zyu4rhq208y1/chrome_2022-11-05_18-55-01.png
- [x] If user search for react, clicks on react project and goes back to homepage by clicking back in the browser he should also get scrolled down to the results since the URL remains "https://www-jsdelivr-com-pr-400.onrender.com/?query=react"
 - [x] Analytics and Stats text can't be selected, and the link can't be clicked
 - [x] List API v2 requests and output in the API examples
 - [x] At https://www-jsdelivr-com-pr-400.onrender.com/custom-cdn-oss, use the same link styles for "[CocoaPods full stats](https://www-jsdelivr-com-pr-400.onrender.com/custom-cdn-oss/cocoa)" links as at the homepage - add animation, remove the underline.
 - [x] Analytics and stats section text and link are not clickable
 - [x] Lets make the logos here clickable to point to their dedicated pages (not their sites, our stats pages) https://dl.dropboxusercontent.com/s/ufd413u0w3p6qvw/chrome_556O07uMeJ.png

Mobile:
- [x] Weird grey hover state when opening dropdowns https://dl.dropboxusercontent.com/s/0fa1b2li2xnul03/chrome_2022-11-05_18-57-39.png
- [x] #494
- [x] If I search for "reac" and click on the results to go to a project, it should change the top search text to the name of the project I am visiting instead of the half text I searched https://dl.dropboxusercontent.com/s/ikh3rcm2kx20zi7/chrome_2022-11-05_19-00-02.png

**Comment by MartinKolarik** [comment]
>  If user search for react, clicks on react project and goes back to homepage by clicking back in the browser he should also get scrolled down to the results since the URL remains "https://www-jsdelivr-com-pr-400.onrender.com/?query=react"

This already happens.

>  Wrong font weight in stats? https://dl.dropboxusercontent.com/s/3mloix2wvcljcrq/chrome_2022-11-05_18-51-29.png

N/A, we agreed to use a different font there, and this is the closest we can get.

**Comment by jimaek** [comment]
>N/A, we agreed to use a different font there, and this is the closest we can get.

Cant we make it bolder?

**Comment by MartinKolarik** [comment]
Only like this which looks even worse: https://dl.dropboxusercontent.com/s/cfc9vga1c3cm2ve/2022-11-06_16-27-15.png

**Comment by jimaek** [comment]
lol nothing in between? Current is too thin and that one is too bold. Something in between would be perfect

**Comment by MartinKolarik** [comment]
Exactly, nothing in between.

**Comment by jimaek** [comment]
> > If user search for react, clicks on react project and goes back to homepage by clicking back in the browser he should also get scrolled down to the results since the URL remains "https://www-jsdelivr-com-pr-400.onrender.com/?query=react"
> 
> This already happens.

I managed to replicate it. It happens only if the page fully loaded, but if you click back before the page finishes loading all the API data it doesnt work.

**Comment by jimaek** [comment]
The package pages are still somewhat annoying to use because the most useful data is loaded last. Here are some notes:

1. This API call is executed twice. Results and query are identical. `https://data-jsdelivr-com-preview.onrender.com/v1/stats/packages/npm/@angular/fire/versions?period=quarter&by=hits&limit=5`
2. We load stats and versions first but it should be entrypoints
3. Entrypoints API call is also executed twice
4. CSS jumps in the install module https://dl.dropboxusercontent.com/s/16sjb2t9aoxd6ez/chrome_cGXQB2bQRQ.mp4

**Comment by MartinKolarik** [comment]
The repeated calls come from different components using the same data. It could be avoided but doesn't matter because the browser deduplicates/caches them. The load order is based on the necessary data flow and is correct. The CSS jump comes from a font swap which you love so much because it's "best practice" for Google.

**Comment by jimaek** [comment]
The calls are still made and they hit the API, they don't use any browser cache it seems. This will impact performance. 

The load order should prioritize the data in the first view which currently just looks bad.

Even on my fast internet and desktop it takes a while for the page to load, the UX is not the best. People with slower hardware and internet will be looking at a broken page for a while before it becomes useful.

I care about SEO which means caring about Google best practices. 

So no need to be passive aggressive, the question is how to fix the above.

**Comment by MartinKolarik** [comment]
> The calls are still made and they hit the API, they don't use any browser cache it seems. This will impact performance.

https://dl.dropboxusercontent.com/s/xth31mh7ibme0zv/2023-01-22_17-54-23.png

> I care about SEO which means caring about Google best practices. So no need to be passive aggressive, the question is how to fix the above.

Sure, my point is simply - it works as intended, this is exactly what should happen when a font swap is used.

**Comment by jimaek** [comment]
I dont see any deduplication or caching https://dl.dropboxusercontent.com/s/yb7xdvhri15457c/chrome_2023-01-22_18-25-23.png

Additionally we make 12 API calls for the packages page. Is it really necessary? Some look very strange to me. I am sure some could be loaded later based on some event and not on page load.

>Sure, my point is simply - it works as intended, this is exactly what should happen when a font swap is used.

Since we're now targeting master we finally have previews working. Lets open a PR without swap see if it removes the jump and the see what Google's tools have to say. I am certain there is a solution that will both avoid the jump and keep Google happy

**Comment by MartinKolarik** [comment]
To be fair, the jump isn't really there under normal conditions with the swap either because you have the font cached. It only happens if you don't have it downloaded yet.

**Comment by jimaek** [comment]
Yes, but it still ruins the first time impression. And when there is no jump I still have to wait for everything to load while looking at a black install screen since it loads last
