### ISSUE TITLE
The url with the search key doesn't scroll to the correct position

### ISSUE THREAD

**Issue by abishekrsrikaanth** [jsdelivr/www.jsdelivr.com#47]
Take a look at this url: http://lb.jimaek.svc.tutum.io/?query=fabri

The scrolling should automatically position to the header being the top element.
Right now it looks like this

![](http://storage4.static.itmages.com/i/15/0803/h_1438581387_9199448_43f19c1cd6.png)

**Comment by MartinKolarik** [comment]
Header - do you mean the red nav bar? Currently it works exactly the way I intended.

**Comment by abishekrsrikaanth** [comment]
So what you see on the screenshot is that how it is intended? Shouldn't the red nav bar stick to the top of the page?

**Comment by MartinKolarik** [comment]
Yes, that's intended. It'll become sticky if you scroll down a little more.

**Comment by abishekrsrikaanth** [comment]
The sticky thing works when you scroll, but the below I feel would be a cleaner one to scroll to...

![](http://i.imgur.com/iHfW09r.png)

Let me know what you think. I am open to other views....

**Comment by MartinKolarik** [comment]
I did it this way so that sponsors are visible as well, and I think it looks pretty good. I'm going to close this as there's no usability problem and I'm not planning to change this.
