### ISSUE TITLE
Scroll to search results broken

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#514]
https://www.jsdelivr.com/?query=react doesn't scroll to search results on load anymore. Similarly, if you click on pagination, it doesn't scroll up. I suspect https://github.com/jsdelivr/www.jsdelivr.com/pull/505 as the source of the problem - make sure the fix of this one doesn't bring #501 back.

**Comment by xbpcb** [comment]
I am not sure it is related to #505 
Here where is the problem
![2023-03-13_14-09](https://user-images.githubusercontent.com/13244319/224697816-e397e6c5-2515-4b7d-bc94-f16b40d6da01.png)

**Comment by MartinKolarik** [comment]
Could also be that the slim jQuery version doesn't have that function. In that case, we should implement our own if not too hard, or revert to full jQuery.

**Comment by MartinKolarik** [comment]
As a hotfix, I added back the full jQuery build. Please see later if we can use our own animation.

**Comment by xbpcb** [comment]
Ok, i will
