### ISSUE TITLE
Clean collection

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#52]
I just realized that there is no way to clean selected files from the collection without finding each project individually and removing it. Thats very annoying

Can we add a button somewhere to fix that? Any ideas?

**Comment by MartinKolarik** [comment]
There is:
![image](https://cloud.githubusercontent.com/assets/6192491/9391626/150d4a7e-4778-11e5-90c0-ded33424e974.png)

**Comment by jimaek** [comment]
Not when you have multiple kinds of files

**Comment by MartinKolarik** [comment]
Why not? All selected files are listed there.

**Comment by jimaek** [comment]
Damn, I missed the button. Maybe we should move it to the center? I bet a lot of people will miss it

**Comment by MartinKolarik** [comment]
You mean the one that reveals the selected files? No problem.

**Comment by jimaek** [comment]
yeah, thank you
