### ISSUE TITLE
Proxied image in readme broken if URL contains percent-encoded percentage

### ISSUE THREAD

**Issue by Krinkle** [jsdelivr/www.jsdelivr.com#520]
The readme of https://github.com/jquery/typesense-minibar/ contains an image from https://img.shields.io. Shields.io page contains an example for code coverage percentages, which this repo uses as-is at URL <https://img.shields.io/badge/coverage-89%25-brightgreen.svg> as follows:

![](https://img.shields.io/badge/coverage-89%25-brightgreen.svg)

At <https://www.jsdelivr.com/package/gh/jquery/typesense-minibar>, this image is broken:

| Screenshot |
|--|
| <img width="590" alt="Screenshot" src="https://user-images.githubusercontent.com/156867/232411375-3b2c08db-6b78-4ac6-9f7b-0f18ac861c0c.png"> |

The error is served from <https://img.jsdelivr.com/img.shields.io/badge/coverage-89%25-brightgreen.svg>, which responds with:

```json
{"error":"bad origin url 'https://img.shields.io'"}
```

Images from same origin without a percent do work <https://img.jsdelivr.com/img.shields.io/badge/coverage-89-brightgreen.svg>:

![](https://img.jsdelivr.com/img.shields.io/badge/coverage-89-brightgreen.svg)

**Comment by jimaek** [comment]
We're looking into this, thanks for reporting

**Comment by jimaek** [comment]
Should be fixed now, thank you for reporting
