### ISSUE TITLE
Scroll gets stuck after search

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#521]
https://dl.dropboxusercontent.com/s/2mh60los8x8vpf4/ArcControl_2023-04-18_14-31-01.mp4

During that weird jumping I was trying to scroll down

**Comment by MartinKolarik** [comment]
Fixed. It's possible this will bring back the issue that you reported in https://github.com/jsdelivr/www.jsdelivr.com/issues/467#issuecomment-1304881680, but right now, I can't replicate either (with the current master). Open a new issue for that if needed.
