### ISSUE TITLE
Share results/CLI switcher

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#528]
Lets add a switcher here https://dl.dropboxusercontent.com/s/pza14homvxb0cxi/chrome_2023-05-02_13-48-04.png that changes the field from a URL to a CLI command that duplicates the test.

Default state would be same as now. It can contain "Share (icon) | CLI (icon)"

This way the user can for example continue using the same test in the terminal

**Comment by jimaek** [comment]
@MartinKolarik any objections?

**Comment by MartinKolarik** [comment]
To the idea no, to the interface... let's try and see how it works.
