### ISSUE TITLE
Fix blog URLs 

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#542]
- sitemap uses ghost.io https://www.jsdelivr.com/blog/sitemap-posts.xml

- Force canonical to always be www.jsdelivr.com

**Comment by MartinKolarik** [comment]
@alexey-yarmosh the blog internally runs at https://jsdelivr-blog.ghost.io/ and we proxy it to www.jsdelivr.com/blog. The first problem is this (it should always be `www.jsdelivr.com`):
![image](https://github.com/jsdelivr/www.jsdelivr.com/assets/6192491/6aa8b85a-09bd-4cbd-9c6a-2146a78cd4f5)

Please check if we can do any of the following to:
 - customize how the link is output (change its value) in [our theme](https://github.com/jsdelivr/ghost-jsdelivr-theme),
 - remove the link in our theme,
 - add a "no index" meta tag in our theme - this one is certainly doable as the last option.

If we go with the third option, we can then simply remove that meta tag in our proxy.

The second issue, the sitemap:
 - again, if we can customize it via the theme, that would be easiest,
 - alternatively, our proxy can be adjusted to override values in XML too (the parser probably supports it), and rewrite the links in the sitemap the same way as we do it for HTML links: https://github.com/jsdelivr/www.jsdelivr.com/blob/master/src/proxy.js

**Comment by alexey-yarmosh** [comment]
Canonical:
- it is not possible to configure the canonical value using admin panel or theme
- as it is a part of a `ghost_head` helper we can copy its output and edit/remove canonical there, but that is dirty
- there is no way to execute code on the server side, before it is sent to the user. And editing link using scripts on FE is too late
- adding a "no index" tag and remove it during proxying is the only option

Sitemap:
- no way to configure values there
- rewrite values on the proxy side seems to be the only option too

**Comment by MartinKolarik** [comment]
@jimaek wdyt, adding no index to the ghost domain should mean canonical doesn't matter and solve the problem, right?

**Comment by jimaek** [comment]
Yes if it works correctly it should be fine

**Comment by MartinKolarik** [comment]
Ok so let's proceed with updating the proxy for both parts and then updating the theme to add the tag.
