### ISSUE TITLE
Google search fixes

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#545]
- [x] On pages like this https://www.jsdelivr.com/package/npm/wz-dt-object and this https://www.jsdelivr.com/package/gh/gaopan812/boke can we detect that its unpublished and add a noindex meta tag? It would be easier than trying to update the sitemap. This way we will get rid of 404s 
- [x] Lets remove from sitemap projects with less than 200 hits for last month, or something similar. They bring no value and Google takes too long to index us. I would prefer to free up Google's capacity for new GP pages
- [x] Google tries to index and 404s on many URLs like this one https://www.jsdelivr.com/assets/67eb11e5dd26da6deef9c74e7ef90b0c387c6692 lets fix or at least add noindex tag
- [x] Google is also trying to index data.jsdelivr URLs like this one https://data.jsdelivr.com/v1/package/npm/typerjs/badge lets also add a noindex to robots.txt maybe
- [x] Tell search engines to ignore query parameters as they seem them duplicate content https://dl.dropboxusercontent.com/s/34odrv56mpyop0q/chrome_2023-05-24_15-47-17.png

**Comment by MartinKolarik** [comment]
For future reference, adding noindex by JS is mentioned directly by Google in: https://developers.google.com/search/docs/crawling-indexing/javascript/javascript-seo-basics#avoid-soft-404s
