### ISSUE TITLE
Package not found on JsDelivr

### ISSUE THREAD

**Issue by strawmelonjuice** [jsdelivr/www.jsdelivr.com#576]
I saw earlier issues like this being solved after a few hours or days, but [my package](https://www.jsdelivr.com/package/npm/hl-img) hasn't shown up in days, while the [npmjs page](https://www.npmjs.com/package/hl-img) has been up since first publish a month ago. Was wondering if there might be an error in caching or maybe something I did wrong?

**Comment by jimaek** [comment]
This is an issue with our search provider, please follow here for more updates: https://github.com/algolia/npm-search/issues/1112. The package is available at the CDN regardless of what the website currently shows.
