### ISSUE TITLE
Version sorting

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#60]
http://www.jsdelivr.com/projects/react
>React lastversion shows 0.14.0-rc1 instead of 0.14.0
https://github.com/jsdelivr/jsdelivr/issues/7281

We should short the versions correctly. 0.14.0 > 0.14.0-rc1 > 0.14.0-beta1

**Comment by MartinKolarik** [comment]
This has already been working, but I removed the sorting part when we switched to using the API. I think this should be handled by the API. If you agree, I can post the correct implementation in JS here.

**Comment by jimaek** [comment]
Yeah, we should do that in the API. I open an issue there. Thanks

**Comment by jimaek** [comment]
https://github.com/jsdelivr/api/issues/104

**Comment by tomByrer** [comment]
IMHO RC & alpha versions don't belong in a public CDN (this is one of the reasons), but I think we had this discussion before ;)

**Comment by MartinKolarik** [comment]
@jimaek I rebuilt the index and it should be OK now.

**Comment by jimaek** [comment]
yup, looks great. Thanks everyone
