### ISSUE TITLE
sub-folder mainfile issue?

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/www.jsdelivr.com#61]
http://www.jsdelivr.com/projects/css3-metro-buttons
Follow the link to: https://cdn.jsdelivr.net/css3-metro-buttons//css/m-buttons.min.css which doesn't work
Here is the [repo](https://github.com/jsdelivr/jsdelivr/tree/master/files/css3-metro-buttons/1.2/css)

**Comment by jimaek** [comment]
Its an API issue, thanks for reporting.

**Comment by jimaek** [comment]
Fixed
