### ISSUE TITLE
[BUG] Link converter doesn't recognise `archive/refs/heads`

### ISSUE THREAD

**Issue by steve02081504** [jsdelivr/www.jsdelivr.com#611]
https://www.jsdelivr.com/github
e.g.
input:
```url
https://github.com/steve02081504/esh/archive/refs/heads/master.zip
```
output(not working):
```url
https://cdn.jsdelivr.net/gh/steve02081504/esh@archive/refs/heads/master.zip
```
![图片](https://github.com/jsdelivr/www.jsdelivr.com/assets/31927825/99e0d8d1-15eb-4bc8-916a-bb748dae75a2)

**Comment by MartinKolarik** [comment]
Hey, these are not supported by the CDN and the URL format is the same as for branches, so I think this is a won't fix.
