### ISSUE TITLE
project linking broken

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/www.jsdelivr.com#63]
1. http://www.jsdelivr.com
2. click on a project
3. project view opens, eg http://www.jsdelivr.com/projects/jquery
4. Copy URL in browser URL bar
5. Close window
6. Paste in new window
7. get 503 server error (& embarrassment when promoting jsDelivr in another project's issue thread)

**Comment by MartinKolarik** [comment]
I restarted the server.

@jimaek did it crash again?

**Comment by jimaek** [comment]
I believe so but cant see the logs because it was too long ago. Did you check logentries for anything helpful?

**Comment by tomByrer** [comment]
To help minimize future damage, I can try to remember to use jsdelivr.com more often.  But could there be an uptime service that checks specific URLs like http://www.jsdelivr.com/projects/jquery that you're already using or are easy to add in?

**Comment by jimaek** [comment]
I created an uptime monitor for that URL.

**Comment by tomByrer** [comment]
great
