### ISSUE TITLE
GP: probes clustering on the map

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#635]
I noticed the coordinates we're getting from geoip providers are very low quality and tend to put all probes in the area in a single place. E.g. [this](https://dl.dropboxusercontent.com/scl/fi/fqds5qa1u8zti96p8cgrp/2024-06-17_23-30-46.png?rlkey=7ygcz1am0tniljx8ijznohi7j&dl=0) changes to [this](https://dl.dropboxusercontent.com/scl/fi/ue2gs9nsy4198jcta7ga0/2024-06-17_23-32-41.png?rlkey=csl7mvus54s3qguqql3etvhbe&dl=0) when zooming, which is 1 probe on the left, and 17 probes stacked over each other on the right. In some other cases, it results in formations like [this](https://dl.dropboxusercontent.com/scl/fi/3ul1loxbckhtw9cyo3d8g/2024-06-17_23-33-51.png?rlkey=k9jl7uai53efxau2xwelyfc94&dl=0). 

We have a somewhat related task https://github.com/jsdelivr/globalping/issues/306 (this question is about UI, but it might create new requirements in that task), and I'm wondering what's even the best way of presenting these on the map:
 a) slightly moving the dots so that each individual probe is visible (similar to the last screenshot),
 b) forcing the cluster view and always showing a single node with the number,
 c) something else?

I think B makes the most sense (with 20 dots, you aren't going to click each of them to see the details anyway), and it allows for the most efficient API responses, but it opens the question of what to do about tooltips with network names - do we just not show them for these clusters? Do we show a big tooltip with all network names?

@jimaek @alexey-yarmosh

**Comment by jimaek** [comment]
I don't want to force the cluster view, I want people to be able to view each individual dot and metadata. So option 1 sounds best

**Comment by MartinKolarik** [comment]
But does that option really work for what you want? If I see 20 probes in one location, I really won't be clicking each of them. It gets boring very quickly. If we show a single big cluster, we can also show all information combined in a single tooltip, which seems better.

**Comment by jimaek** [comment]
I personally often use it and zoom all the way to the dots to better understand what is going on and where exactly is probe is. Just having "20 probes in this general direction" is not very nice or precise.

**Comment by MartinKolarik** [comment]
But we're talking specifically about the case where all probes are in the same location anyway. If the coordinates were different, we would still show them separately.

**Comment by jimaek** [comment]
How would the tooltip look in that case? There are instances of 20 probes in the same coordinates

**Comment by MartinKolarik** [comment]
We now have this behavior on the new network page. @xbpcb please port the coordinates grouping to the homepage as well.

So on the homepage:
 - clustering remains as is (big hexagonal clusters),
 - probes that have the exact same coordinates are displayed as one, with the number and new tooltip,
 - the grouping doesn't apply when showing test results.
