### ISSUE TITLE
Update URL when re-running a test

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#646]
1. Open https://www.jsdelivr.com/globalping?measurement=KS9UnAf2HP7jww3u
2. Change the hostname and re-run
3. The URL remains the same but now it no longer makes sense

Can we clear the URL to https://www.jsdelivr.com/globalping if the user opens a shared URL and runs a new test?

**Comment by MartinKolarik** [comment]
Actually, let's update the URL to the current measurement any time a measurement is finished. That'll make sharing and navigating between results much easier.
