### ISSUE TITLE
Hitting homepage directly via a URL with query param returns a 503

### ISSUE THREAD

**Issue by Craga89** [jsdelivr/www.jsdelivr.com#66]
If you hit the main jsDelivr website with the `query` parameter set it returns a 503.

Example: https://www.jsdelivr.com/?query=qtip2

**Comment by MartinKolarik** [comment]
Works now.

@jimaek I'm working on a long-term solution.

**Comment by jimaek** [comment]
@MartinKolarik Thanks
@Craga89 Your new version is live http://www.jsdelivr.com/projects/qtip2

**Comment by Craga89** [comment]
:+1: Awesome, that'll make putting releases out much easier. Nice work on the automation @jimaek, very impressive
