### ISSUE TITLE
GP: blog

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#682]
@jimaek I think it isn't ready yet, right?

**Comment by jimaek** [comment]
Not yet. I'm also thinking, do we want to do /blog or subdomain?
I kind of want to avoid all the proxying and rewriting stuff

**Comment by MartinKolarik** [comment]
I'm good with both options. Subdomain is easier.

**Comment by jimaek** [comment]
Its live with all content moved, same passwords too https://blog.globalping.io/
