### ISSUE TITLE
Sponsors too big on mobile

### ISSUE THREAD

**Issue by franciscop** [jsdelivr/www.jsdelivr.com#71]
What I can see from my mobile (with a bit of zoom to be able to read the text):

![screenshot_2016-06-08-17-38-36](https://cloud.githubusercontent.com/assets/2801252/15900545/267447f4-2da0-11e6-8b25-247930c2dbef.png)

Without any zoom is not so bad, but still too much space (and the font is definitely too small to read on my screen):

![screenshot_2016-06-08-17-42-56](https://cloud.githubusercontent.com/assets/2801252/15900643/8eee7160-2da0-11e6-92f3-a342bce77313.png)

**Comment by jimaek** [comment]
I am honestly curious why would anyone visit our website on mobile. The point is to copy a URL and use it in your website. You wont be coding on your phone

**Comment by franciscop** [comment]
I *have* done some quick and small experiments in jsfiddle, mainly while in public, long transportation after programming (when I take some time to think and it occurs to me, maybe if I did ... ).

This is also an issue with split screen, which is not my user-case but it might be for others.

The problem for me came when I wanted to check if [my library was correctly updated](https://github.com/jsdelivr/jsdelivr/pull/12015).

Do you get 0-1% of visits from mobile so it's a not important issue? Or do you get a number of visits large enough to justify it? Besides, if no one is expected to visit the website on mobile, and it'd only take about 3 lines to hide the sponsor header on mobile, then it's a no-brainer to do it.

**Comment by MartinKolarik** [comment]
@jimaek would it be ok to make sponsors non-sticky on small screens? The menu + sponsors really do take about 70% of the screen.

**Comment by jimaek** [comment]
Sure, you can make the logos smaller as well if you want
