### ISSUE TITLE
Extraneous space in package URL copied from /esm

### ISSUE THREAD

**Issue by lubieowoce** [jsdelivr/www.jsdelivr.com#717]
### Description

If i select and copy the package URL displayed on https://www.jsdelivr.com/esm, it will contain a space before the module name.

### Reproduction steps

> [!NOTE]
> this issue seems to affect Firefox 133 (MacOS) and Safari 17.6. I can't reproduce it in Chrome 131.

Selection:

<img width="705" alt="Screenshot 2024-12-17 at 15 27 57" src="https://github.com/user-attachments/assets/1805d820-805c-44e3-a589-fa7134603dfe" />

Clipboard contents after copying:
```
'https://esm.run/ d3' 
```

I believe this is because the package name is in a separate span with a newline + whitespace before it (which gets collapsed to a single space)
https://github.com/jsdelivr/www.jsdelivr.com/blob/74295c104ff9f327b70684ef2f8741187b4d2e8c/src/views/pages/esm.html#L33-L34

### Expected behavior

I would like the URL to be copyable as-is, without needing to remove the space.

**Comment by MartinKolarik** [comment]
@lubieowoce should be fixed in ~10 minutes, please check then.

**Comment by lubieowoce** [comment]
Ah, you were faster than me :D thanks!

**Comment by lubieowoce** [comment]
@MartinKolarik https://github.com/jsdelivr/www.jsdelivr.com/commit/aa63589e39af09637d91224dd01cf3c4230d4804 fixed it for me in firefox, but safari still seems to have the same issue... maybe just getting rid of the span is easier?
https://github.com/jsdelivr/www.jsdelivr.com/pull/718

**Comment by MartinKolarik** [comment]
Thanks, I don't have Safari at hand so please try again in a few minutes.

**Comment by lubieowoce** [comment]
just tested in safari, works fine now!
