### ISSUE TITLE
Allow clearing collection

### ISSUE THREAD

**Issue by julmot** [jsdelivr/www.jsdelivr.com#72]
When adding something to the collection and later working on another thing with different dependencies I'm missing a button to clear the local storage containing the previous collection. I'm expecting it inside the "collection" dialog.

**Comment by MartinKolarik** [comment]
In case you don't know, it is possible do remove projects without searching for each of them:

![image](https://cloud.githubusercontent.com/assets/6192491/16411471/7ec904c6-3d27-11e6-98be-288b06be20b0.png)

That said, I agree that a "clear all" button would be useful.

**Comment by julmot** [comment]
I agree, even if there are such things like you've said it would be helpful though.

However, I don't have the things in your screenshot:

![2016-06-28_123919](https://cloud.githubusercontent.com/assets/8310677/16412600/5eba4176-3d2d-11e6-861b-f98125e4206c.png)
![2016-06-28_123926](https://cloud.githubusercontent.com/assets/8310677/16412601/5ec947c0-3d2d-11e6-809d-4dad892777e4.png)

Maybe a browser issue? I am using FF 47 and don't have any error messages in the console.

**Comment by MartinKolarik** [comment]
You need to click the little arrow button in the middle to reveal the list of files.

**Comment by julmot** [comment]
From my point of view this arrow button is completely misplaced. I don't think that users will find this feature... I think a usability A/B test would be helpful here.

**Comment by MartinKolarik** [comment]
@jimaek thoughts? I think the button should be easy to spot.

**Comment by jimaek** [comment]
For now lets leave it. Its a not a huge problem and we dont have the resources to do A/B testing and such.
