### ISSUE TITLE
Contact email does not work

### ISSUE THREAD

**Issue by lidel** [jsdelivr/www.jsdelivr.com#73]
> ```
> This is the mail system at host server33.cretaforce.gr.
> 
> I'm sorry to have to inform you that your message could not
> be delivered to one or more recipients. It's attached below.
> 
> For further assistance, please send mail to postmaster.
> 
> If you do so, please include this problem report. You can
> delete your own text from the attached returned message.
> 
>                    The mail system
> 
> <contact@jsdelivr.com>: host server33.cretaforce.gr[private/dovecot-lmtp] said:
>     552 5.2.2 <contact@jsdelivr.com> Not enough disk quota (in reply to end of
>     DATA command)
> ```

**Comment by jimaek** [comment]
Thanks for letting me know. It will be fixed soon. You can email me directly if you want. (email in my github profile)

**Comment by lidel** [comment]
Thanks, but I already created https://github.com/jsdelivr/www.jsdelivr.com/issues/74. 
I hope it is the right place for this.
