### ISSUE TITLE
JS responsible for SRI generation does not work

### ISSUE THREAD

**Issue by lidel** [jsdelivr/www.jsdelivr.com#74]
CORS headers are missing and it breaks SRI generation:

>  ![2016-07-01-185751_957x860_scrot](https://cloud.githubusercontent.com/assets/157609/16529058/f452f7c4-3fc0-11e6-840b-e2edef42bddf.png)

Workaround is to generate SRI manually (https://www.srihash.org/)

**Comment by jimaek** [comment]
Can you give me the HTTP headers when you are requesting one of the broken files?

**Comment by MartinKolarik** [comment]
We are loading the files directly from the CDN which *does* send the correct headers. Not sure where the problem might be.

**Comment by lidel** [comment]
Turns out the issue I was experiencing was caused by [HTTPS Anywhere](https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/) addon. 

I was on http://www.jsdelivr.com, however the addon replaced XHR requests with HTTPS ones (and  CORS information got lost in the process).

After I disabled it for jsDelivr, everything got back to normal and SRI was generated correctly.

**Comment by jimaek** [comment]
:+1:
