### ISSUE TITLE
Add maplatency to Gold sponsors

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#77]
Link to www.maplatency.com/?pk_campaign=jsdelivr 

Logo will be provided

**Comment by jezowicz** [comment]
Attaching here few sizes, depending what is more suitable.

![300x300_white](https://cloud.githubusercontent.com/assets/12803080/20487519/f8626062-b003-11e6-83d0-cee71d582768.png)
![big_transparent](https://cloud.githubusercontent.com/assets/12803080/20487518/f8604188-b003-11e6-963d-d87f80a7877b.png)
![logo_white_bg_small](https://cloud.githubusercontent.com/assets/12803080/20487517/f85fc1d6-b003-11e6-9c4b-aee8808047d3.png)

If you could also place Alt text to > Speedchecker - Test ping latency worldwide

**Comment by jimaek** [comment]
@MartinKolarik Can you also add them to footer? I forgot about that

**Comment by MartinKolarik** [comment]
Done.

**Comment by MartinKolarik** [comment]
@jimaek looks like auto deployment doesn't work?

**Comment by jimaek** [comment]
Stupid Docker, everything always breaks. I triggered a deploy manually. Hopefully it will work

**Comment by MartinKolarik** [comment]
[Travis says something about wrong API key.](https://travis-ci.org/jsdelivr/www.jsdelivr.com/builds/180569335)
