### ISSUE TITLE
Add Packet.net to gold sponsors

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#79]
https://assets.packet.net/company/logo.svg

Description "Packet is a bare metal cloud built for developers. 8 minute deploys, no hypervisor, and full automation support from datacenters in NYC, SJC, NRT, and AMS."

* Logo + link in footer
* Logo + link below Platinum sponsors in "Sponsors" page. Small description

**Comment by jimaek** [comment]
@MartinKolarik Give this a priority please

**Comment by MartinKolarik** [comment]
@jimaek please deploy
