### ISSUE TITLE
Add subscribe button

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#80]
We should replace the top right "add project' button with "Subscribe"  http://eepurl.com/cJjjDj

**Comment by MartinKolarik** [comment]
👍 just a quick question: do we need the first and last name in the form?

**Comment by MartinKolarik** [comment]
![image](https://cloud.githubusercontent.com/assets/6192491/24586703/34f6152c-17a7-11e7-98ff-0a2490617bef.png)

Both buttons or just the first?

**Comment by jimaek** [comment]
Lets do both buttons. Only the first name is required, the other is optional
