### ISSUE TITLE
File names with literal plus character not supported?

### ISSUE THREAD

**Issue by sbrandtb** [jsdelivr/www.jsdelivr.com#81]
I'm trying to deliver [riotjs](https://www.jsdelivr.com/projects/riot) with jsdelivr. One of their files is named `riot+compiler.min.js`. If I'm trying to deliver it in a group, the generated URL fails because it thinks that the files `riot` and `compiler.min.js` are requested:

```
curl "https://cdn.jsdelivr.net/g/riot@3.4.2(riot+compiler.min.js)"

Could not find file riot for project: riot.⏎  
```

* Is there any way to escape the plus so the CDN will not fail?
* If there is, it IMO should be added to the URL generation
* If not, should we fix it?

**Comment by jimaek** [comment]
Its not possible right now, but it will work when we release our new backend in a month or so.
Until then use direct links without combination

**Comment by sbrandtb** [comment]
Thanks for resolving!

Just in case anyone comes along and wonders about the actual "fix":

```
curl "https://cdn.jsdelivr.net/riot/3.4.2/riot+compiler.min.js"

[lots of JS]
```

**Comment by MartinKolarik** [comment]
Interesting. Didn't realize this works with the new version.

**Comment by MartinKolarik** [comment]
Closing as it works with beta, which will go live soon: http://beta.jsdelivr.net/riot/3.4.2/riot+compiler.min.js

**Comment by sbrandtb** [comment]
Using the non-grouped download is not the issue. The grouped one is!

```
curl "https://cdn.jsdelivr.net/riot/3.4.2/riot+compiler.min.js"
-> works with the current version already!

curl "http://beta.jsdelivr.net/g/riot@3.4.2(riot+compiler.min.js)"
Couldn't find the requested file /riot in riot.⏎
```

The bug is *not* fixed on the `beta.jsdelivr.net` host.

**Comment by MartinKolarik** [comment]
Sorry, wrong link. `/g/` works too if you encode the plus sign: http://beta.jsdelivr.net/g/riot@3.4.2(riot%2Bcompiler.min.js)

**Comment by sbrandtb** [comment]
Alright, thank you
