### ISSUE TITLE
Replace keycdn with fastly

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#82]
Replace KeyCDN with fastly on all pages of the site. Push it when you can within the week
![fastly_logo-01](https://cloud.githubusercontent.com/assets/1834071/25587508/aa13ae32-2ea4-11e7-998b-c69c5771d62b.png)

**Comment by MartinKolarik** [comment]
Description for sponsors page?
Value of `Server` header for Fastly?
I suppose I should skip stats?

**Comment by jimaek** [comment]
* Fastly’s edge cloud platform powers fast, secure, and scalable digital experiences.
* "Value of Server header for Fastly?" where do we need that?
* Yes, skip them for now

**Comment by MartinKolarik** [comment]
>"Value of Server header for Fastly?" where do we need that?

On the homepage to highlight the used provider.

**Comment by jimaek** [comment]
I think we can use `x-served-by` for that

**Comment by MartinKolarik** [comment]
Ok but you'll need to add it to `Access-Control-Expose-Headers` at `/information.txt` and tell me the value to look for.

**Comment by jimaek** [comment]
Test it https://fastly.jsdelivr.net/framy/2/css/framy.min.css

If any value is set then its Fastly.

**Comment by MartinKolarik** [comment]
It works but I'll need you to add it to `access-control-expose-headers` as mentioned earlier.

**Comment by jimaek** [comment]
Its already there https://fastly.jsdelivr.net/information.txt

**Comment by MartinKolarik** [comment]
![image](https://cloud.githubusercontent.com/assets/6192491/25762060/883e9876-31dd-11e7-91b4-f890f56015f1.png)
