### ISSUE TITLE
Add Risingstack

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#83]
![risingstack_color](https://cloud.githubusercontent.com/assets/1834071/25755638/092cfeba-31c4-11e7-89d6-9b92d4d44a5b.png) link https://risingstack.com/

"RisingStak helps with node.js consulting, training and development"

Add them to premium sponsors.

**Comment by MartinKolarik** [comment]
>premium sponsors

platinum?

**Comment by jimaek** [comment]
yes sorry

**Comment by MartinKolarik** [comment]
please deploy

**Comment by jimaek** [comment]
Deployed, looks good. Update logo when you have time https://risingstack.com/static/images/risingstack-logo-2017-white.svg

**Comment by MartinKolarik** [comment]
>Update logo when you have time

Also on sponsors page or just navbar?

**Comment by MartinKolarik** [comment]
Ok on sponsors page definitely not since it wouldn't be visible 😄

**Comment by jimaek** [comment]
haha yeah. Navbar looks good as is I think. So I think only homepage needs it. And now that I think about it I think only the text needs to change from grey to white. To match our current style for the logos

**Comment by MartinKolarik** [comment]
![image](https://cloud.githubusercontent.com/assets/6192491/25765272/6f1c0252-31ec-11e7-8729-9bc4f0e351e8.png)

![image](https://cloud.githubusercontent.com/assets/6192491/25765301/94d56cd6-31ec-11e7-8e38-0e5059a20220.png)

**Comment by jimaek** [comment]
@gergelyke

**Comment by gergelyke** [comment]
Your call, whatever you feel more comfortable with

**Comment by jimaek** [comment]
I think color+white text makes more sense.

**Comment by gergelyke** [comment]
Okay, then let's go for it. 

Also, while you are at it, can you please change the sponsor text to:

```
RisingStack enables amazing companies to succeed with Node.js and related technologies to stay ahead of the competition. RisingStack provides professional Node.js development and consulting services from the early days of Node.js.
```

**Comment by MartinKolarik** [comment]
Done.
