### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#85]

**Comment by MartinKolarik** [comment]
We will start working on a new website soon and would love to hear your ideas and feedback. Here's one of the most recent homepage previews I've made last year - it is far from complete but it gives you and idea of what we want to do.

![01---home---docs---4](https://cloud.githubusercontent.com/assets/6192491/25877588/a5b8ab36-3524-11e7-9136-39f13df62501.png)

**Comment by jimaek** [comment]
- I think we can make the sponsor logos a bit smaller
- Auto-optimization button no longer makes sense
- I think 2 columns is too confusing
- We should make search use npm exclusively. Too hard to support github, plus it would be all duplicates anyway
- Too much wasted space? We should make some elements smaller and remove some of the empty space
- I dont remember, how does the "wordpress" button work?


@MartinKolarik Let me know of your feedback and I can send all this to a designer to make the changes for us.

**Comment by MartinKolarik** [comment]
Just a very short feedback for now:
 - maybe, I think I just kept the current size
 - still does
 - we don't have anything better to use the space for on large screens (on smaller ones it would be one column)
 - need to discuss that later but ideally we want both + also old projects
 - I think it's good but open for specific suggestions
 - I guess it "doesn't" yet, i.e. we didn't really discuss that I think
