### ISSUE TITLE
Purge API

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#87]
We need a basic purge API that will purge a URL from all CDNs.

Ideally should work in browser and via curl too. Needs ability to purge multiple URLs. Should have limits per IP.

Request from user:
>It seems doable to provide an npm token, check for publish rights, and allow clearing cache maybe? http://blog.npmjs.org/post/118393368555/deploying-with-npm-private-modules

**Comment by MartinKolarik** [comment]
👍 if we can make this authenticated. Abuse was one of my concerns.

**Comment by jimaek** [comment]
I was thinking about this. The purge API and CDN stats(the ones currently showed on the stats page) require the exact same information to work. They just do a slightly different function. I think it would make sense to have 1 service do both instead of duplicating the code.
