### ISSUE TITLE
New map

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/www.jsdelivr.com#88]
- Use google maps or other free alternative
- Can we use a .txt file to store a list of cities:provider combination and have the map figure out the locations and automatically put the points on the map?

**Comment by MartinKolarik** [comment]
Do we have the list anywhere?

**Comment by jimaek** [comment]
We have this https://raw.githubusercontent.com/jsdelivr/jsdelivr/master/network.geojson
but its outdated

**Comment by jimaek** [comment]
Also its impossible to maintain it manually. I was using mapbox to edit it. So we should convert it to a human friendly format

**Comment by MartinKolarik** [comment]
Converting to another format isn't a problem but how do we add the missing POPs? Manually?

**Comment by jimaek** [comment]
yes, check the site for the rendered map, then edit the file to add POPs. Something like
maxcdn=london
fastly=warsaw
...
