### ISSUE TITLE
Module listing no longer updated after new backend?

### ISSUE THREAD

**Issue by jhabdas** [jsdelivr/www.jsdelivr.com#93]
I tried to understand why my npm package is no longer updated on the website: https://www.jsdelivr.com/projects/fetch-inject

It's pulled from NPM as expected and [everything there](https://cdn.jsdelivr.net/npm/fetch-inject) works great. Is there some action required on my part to allow Fetch Inject to start seeing new versions on the website?

**Comment by MartinKolarik** [comment]
https://github.com/jsdelivr/jsdelivr/issues/18007#issuecomment-304534797

**Comment by jhabdas** [comment]
I shoulda known. Thanks @MartinKolarik

**Comment by MartinKolarik** [comment]
Our new website is live https://www.jsdelivr.com/. You should see all versions of your package listed now.
