### ISSUE TITLE
Questions regarding npm search

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#98]
1. Are those the credentials we should use on our website: `OFCNCOG2CU`, `f54e21fa3a2a0160595bb058179bfb1e` ?
2. Is it possible to allow searching by package owner using facet filters?
3. Can we link images from https://res.cloudinary.com/hilnmyskv/image/fetch/w_40,h_40,f_auto,q_80,fl_lossy/https://gravatar.com/avatar/7ef42b051ff52ce54535377bf007fec3 ?
4. `package.description` appears to be HTML encoded. Is it safe to render it as html rather than text?

**Comment by MartinKolarik** [comment]
// cc @Jerskouille @vvo @Haroenv

**Comment by Haroenv** [comment]
Yes
Yes
Yes (but someone else should confirm)
Yes

Glad you're making use of t!

**Comment by jimaek** [comment]
Regarding 3, no need to use their links. We can just go to gravatar directly
https://gravatar.com/avatar/7ef42b051ff52ce54535377bf007fec3?s=40
https://res.cloudinary.com/hilnmyskv/image/fetch/w_40,h_40,f_auto,q_80,fl_lossy/https://gravatar.com/avatar/7ef42b051ff52ce54535377bf007fec3

Same thing

**Comment by vvo** [comment]
^ Exactly. Otherwise @Haroenv got it right

**Comment by MartinKolarik** [comment]
The thing is in most cases the avatar links to GitHub and GitHub images are much larger than we need: https://github.com/facebook.png

**Comment by jimaek** [comment]
They have the same parameter https://avatars3.githubusercontent.com/u/69631?s=40

**Comment by MartinKolarik** [comment]
Awesome. Thank you all for the fast responses.

**Comment by MartinKolarik** [comment]
One more question: can we get `browse()` API allowed by any chance?

**Comment by Jerskouille** [comment]
I think we'll be able to provide you with a specific API key w/ search + browse (cc @Haroenv) for this. Is this for the infinite scroll ?

**Comment by MartinKolarik** [comment]
Right now only for a sitemap. Your API seems like the fastest way to retrieve names of all npm packages. Later we might use it somewhere in the UI too.

**Comment by vvo** [comment]
If you are only looking for all the package names, this package has it: https://github.com/nice-registry/all-the-package-names

updated daily I think

**Comment by MartinKolarik** [comment]
@vvo thanks! That seems like exactly what I needed.
