### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/www.jsdelivr.com#99]
Stuff I'm aware is missing:
 - [x] About + FAQ + migrate docs
 - [x] SRI page

**Comment by jimaek** [comment]
I also think we need a sitemap.xml file

**Comment by MartinKolarik** [comment]
You mean all packages or just the other pages?

**Comment by jimaek** [comment]
Definitely for the pages. For all packages depends on difficulty

**Comment by MartinKolarik** [comment]
If it were just for the pages, we don't really need it. I'll see how difficult it would be at least for all npm packages.
